// Curriculum data for the AI Security & Trustworthy Systems path.
//
// This module holds data only. It is rendered by
// preview-app/src/components/CurriculumGraph.jsx, which owns all the drawing
// logic shared by the four career paths.
//
// Course fields:
//   id        short stable key, shown on the node
//   phase     which phase column the node sits in
//   row       row within that column; must be 0..n-1 with no gaps or repeats
//   priority  critical | desirable | frontier
//   kind      spine (every track) | branch (chosen track only) | elective
//   tracks    ["all"] for spine nodes, otherwise the track ids that need it
//   prereqs   ids of the nodes that must come first
//   desc      one or two sentences shown in the detail panel
//   res       recommended resources, separated by "|"

// Phases are drawn left to right in the order listed here.
export const PHASES = [
  { id: "P0", label: "Foundations", subtitle: "Security, systems & CS", color: "#94a3b8" },
  { id: "P1", label: "Phase 1", subtitle: "AppSec & secure coding", color: "#ef4444" },
  { id: "P2", label: "Phase 2", subtitle: "DevSecOps & supply chain", color: "#f97316" },
  { id: "P3", label: "Phase 3", subtitle: "Cloud & infra security", color: "#f59e0b" },
  { id: "P4", label: "Phase 4", subtitle: "Cryptography & identity", color: "#10b981" },
  { id: "P5", label: "Phase 5", subtitle: "AI/ML security", color: "#8b5cf6" },
  { id: "P6", label: "Phase 6", subtitle: "Detection & response", color: "#06b6d4" },
  { id: "P7", label: "Phase 7", subtitle: "Governance, risk & compliance", color: "#3b82f6" },
  { id: "P8", label: "Phase 8", subtitle: "Frontier & leadership", color: "#ec4899" },
];

// Specialization tracks. Node stripes and the filter buttons are coloured
// from this map, and the counts on the page are derived from its size.
export const TRACKS = {
  appsec:    { color: "#ef4444", label: "Application security",      short: "AppSec"    },
  devsecops: { color: "#f97316", label: "DevSecOps & supply chain",  short: "DevSecOps" },
  cloudsec:  { color: "#0ea5e9", label: "Cloud & infra security",    short: "Cloud"     },
  aisec:     { color: "#8b5cf6", label: "AI/ML & LLM security",      short: "AI security" },
  grc:       { color: "#10b981", label: "Governance, risk & compliance", short: "GRC"   },
};

export const COURSES = [
  // ─── P0 ─ Foundations: Security, Systems & CS ─
  { id: "LINUX", phase: "P0", row: 0, label: "Linux & CLI",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Shell fluency, processes, permissions, systemd, packet basics: the substrate every attack and defense runs on.",
    res:  "Linux Journey (🆓) | MIT Missing Semester (🆓) | OverTheWire Bandit wargame (🆓)" },
  { id: "PY", phase: "P0", row: 1, label: "Python",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Scripting tooling, parsing, HTTP clients, and glue for scanners and CI checks: the security engineer's default language.",
    res:  "Automate the Boring Stuff (🆓) | Black Hat Python, Seitz (💰) | requests / httpx docs (🆓)" },
  { id: "NET", phase: "P0", row: 2, label: "Networking & protocols",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "TCP/IP, DNS, TLS handshake, HTTP semantics, proxies and NAT: you cannot secure traffic you cannot read.",
    res:  "Computer Networking: A Top-Down Approach (book) | Wireshark docs & captures (🆓) | Cloudflare Learning Center (🆓)" },
  { id: "WEB", phase: "P0", row: 3, label: "Web platform & HTTP",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["NET"],
    desc: "Browsers, cookies, CORS, same-origin policy, the request/response lifecycle: the attack surface most security careers touch.",
    res:  "MDN Web Docs (🆓) | PortSwigger Web Security Academy (🆓) | web.dev security (🆓)" },
  { id: "OS", phase: "P0", row: 4, label: "OS internals & memory model",
    priority: "desirable", kind: "branch", tracks: ["appsec"], prereqs: [],
    desc: "Processes, syscalls, virtual memory, the stack/heap: the mental model behind memory-safety bugs and exploitation.",
    res:  "OSTEP, Operating Systems: Three Easy Pieces (🆓) | Nand2Tetris (🆓) | pwn.college (🆓)" },
  { id: "THREAT", phase: "P0", row: 5, label: "Security fundamentals & threat modeling",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "CIA triad, trust boundaries, attacker goals, and STRIDE/attack-tree threat modeling: how to reason about risk before writing a control.",
    res:  "Threat Modeling, Shostack (💰) | OWASP Threat Modeling Cheat Sheet (🆓) | CompTIA Security+ objectives (🆓)" },
  { id: "GO", phase: "P0", row: 6, label: "Go / systems programming",
    priority: "desirable", kind: "elective", tracks: ["devsecops", "cloudsec"], prereqs: [],
    desc: "The language of cloud-native and security tooling (Kubernetes, Trivy, Terraform providers): a high-leverage second language.",
    res:  "A Tour of Go (🆓) | Go by Example (🆓) | The Go Programming Language, Donovan & Kernighan (💰)" },

  // ─── P1 ─ AppSec & Secure Coding ─
  { id: "OWASP", phase: "P1", row: 0, label: "OWASP Top 10 & web vulns",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["WEB", "THREAT"],
    desc: "Injection, broken access control, SSRF, XSS, deserialization: the canonical vulnerability classes, hands-on in a lab.",
    res:  "OWASP Top 10 (🆓) | PortSwigger Web Security Academy labs (🆓) | PentesterLab (freemium)" },
  { id: "SECCODE", phase: "P1", row: 1, label: "Secure coding & code review",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["PY", "OWASP"],
    desc: "Input validation, output encoding, safe defaults, and reviewing a diff for the vulnerability the linter missed.",
    res:  "OWASP Cheat Sheet Series (🆓) | OWASP ASVS (🆓) | Secure by Design, Johnsson et al. (💰)" },
  { id: "AUTHZ", phase: "P1", row: 2, label: "AuthN/AuthZ & session security",
    priority: "critical", kind: "branch", tracks: ["appsec", "cloudsec"], prereqs: ["WEB"],
    desc: "Password storage, session tokens, MFA, RBAC/ABAC, and the access-control bugs that top every breach report.",
    res:  "OWASP Authentication & Session Cheat Sheets (🆓) | PortSwigger access control labs (🆓) | NIST SP 800-63B (🆓)" },
  { id: "SAST", phase: "P1", row: 3, label: "SAST / DAST & fuzzing",
    priority: "critical", kind: "branch", tracks: ["appsec", "devsecops"], prereqs: ["SECCODE"],
    desc: "Static/dynamic analysis, semantic queries and coverage-guided fuzzing: automating the search for bugs at scale.",
    res:  "Semgrep & CodeQL docs (🆓) | OWASP ZAP (🆓) | Google/OSS-Fuzz & libFuzzer docs (🆓)" },
  { id: "APPSEC_TEST", phase: "P1", row: 4, label: "Pentesting & exploitation basics",
    priority: "desirable", kind: "branch", tracks: ["appsec"], prereqs: ["OWASP", "OS"],
    desc: "Recon, exploitation, and privilege escalation on deliberately vulnerable targets: thinking like the attacker you defend against.",
    res:  "TryHackMe & Hack The Box (freemium) | HackTricks (🆓) | PEN-200/OSCP, OffSec (💰)" },
  { id: "API", phase: "P1", row: 5, label: "API & mobile security",
    priority: "desirable", kind: "branch", tracks: ["appsec"], prereqs: ["OWASP", "AUTHZ"],
    desc: "REST/GraphQL abuse, broken object-level authorization (BOLA), rate limiting, and mobile client/transport pitfalls.",
    res:  "OWASP API Security Top 10 (🆓) | OWASP MASVS/MASTG (🆓) | PortSwigger GraphQL & API labs (🆓)" },

  // ─── P2 ─ DevSecOps & Supply Chain ─
  { id: "CICD", phase: "P2", row: 0, label: "CI/CD security",
    priority: "critical", kind: "branch", tracks: ["devsecops"], prereqs: ["SECCODE"],
    desc: "Hardening pipelines against poisoned builds, token theft and privileged runners: the CI system is production.",
    res:  "OWASP CI/CD Security Top 10 (🆓) | GitHub Actions security hardening docs (🆓) | SLSA framework (🆓)" },
  { id: "IAC", phase: "P2", row: 1, label: "IaC & policy as code",
    priority: "critical", kind: "branch", tracks: ["devsecops", "cloudsec"], prereqs: ["CICD"],
    desc: "Terraform/OpenTofu security, and codifying guardrails with OPA/Rego and Conftest so misconfig fails the build.",
    res:  "Terraform & OpenTofu docs (🆓) | Open Policy Agent / Rego (🆓) | Checkov & tfsec (🆓)" },
  { id: "CONTAINER", phase: "P2", row: 2, label: "Container & Kubernetes security",
    priority: "critical", kind: "branch", tracks: ["devsecops", "cloudsec"], prereqs: ["LINUX", "IAC"],
    desc: "Image hardening, rootless containers, admission control, network policy, RBAC and runtime detection in the orchestrator.",
    res:  "Kubernetes security docs & CIS Benchmark (🆓) | Falco & Trivy (🆓) | Container Security, Rice (💰)" },
  { id: "SUPPLY", phase: "P2", row: 3, label: "Software supply chain & SBOM",
    priority: "critical", kind: "branch", tracks: ["devsecops"], prereqs: ["CICD"],
    desc: "Artifact signing, provenance, SBOMs and reproducible builds: defending against the dependency and build-system attacks now dominating headlines.",
    res:  "SLSA & in-toto (🆓) | Sigstore / cosign (🆓) | CycloneDX & SPDX SBOM specs (🆓)" },
  { id: "SECRETS", phase: "P2", row: 4, label: "Secrets management",
    priority: "critical", kind: "branch", tracks: ["devsecops", "cloudsec"], prereqs: ["CICD"],
    desc: "Vaulting, dynamic/short-lived credentials, secret scanning and rotation: keeping keys out of git and out of memory dumps.",
    res:  "HashiCorp Vault docs (🆓) | gitleaks & trufflehog (🆓) | Cloud secrets-manager docs (🆓)" },
  { id: "DEPMGMT", phase: "P2", row: 5, label: "Dependency & vulnerability management",
    priority: "desirable", kind: "branch", tracks: ["devsecops"], prereqs: ["SAST"],
    desc: "SCA, CVE triage, reachability analysis and prioritization with EPSS/KEV so you patch what actually matters.",
    res:  "OWASP Dependency-Check & Dependabot (🆓) | OSV & FIRST EPSS (🆓) | CISA Known Exploited Vulnerabilities catalog (🆓)" },

  // ─── P3 ─ Cloud & Infrastructure Security ─
  { id: "CLOUDSEC", phase: "P3", row: 0, label: "Cloud security fundamentals",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["NET", "THREAT"],
    desc: "The shared-responsibility model, the well-architected security pillar, and the primitives across AWS, Azure and GCP.",
    res:  "AWS/Azure/GCP well-architected security docs (🆓) | CIS Benchmarks (🆓) | flAWS & CloudGoat labs (🆓)" },
  { id: "IAM", phase: "P3", row: 1, label: "Cloud IAM & least privilege",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["CLOUDSEC", "AUTHZ"],
    desc: "Policies, roles, federation, privilege-escalation paths and right-sizing entitlements: cloud breaches are IAM breaches.",
    res:  "AWS IAM & Azure Entra docs (🆓) | Cloud IAM privilege-escalation research, Rhino Security (🆓) | Permiso/PMapper tooling (🆓)" },
  { id: "NETSEC", phase: "P3", row: 2, label: "Network security & zero trust",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["NET", "CLOUDSEC"],
    desc: "Segmentation, VPCs, firewalls, service mesh mTLS and the identity-centric zero-trust model that replaces the perimeter.",
    res:  "NIST SP 800-207 Zero Trust Architecture (🆓) | BeyondCorp papers, Google (🆓) | Cloud networking security docs (🆓)" },
  { id: "CSPM", phase: "P3", row: 3, label: "CSPM & cloud posture",
    priority: "desirable", kind: "branch", tracks: ["cloudsec", "devsecops"], prereqs: ["CLOUDSEC", "IAC"],
    desc: "Continuous posture scanning, drift detection and misconfiguration remediation across accounts and clouds.",
    res:  "Prowler & ScoutSuite (🆓) | Steampipe / CloudQuery (🆓) | CIS cloud benchmarks (🆓)" },
  { id: "LOGGING", phase: "P3", row: 4, label: "Logging, monitoring & SIEM",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["CLOUDSEC"],
    desc: "Centralized telemetry, audit trails, log integrity and a SIEM that turns events into alerts you can act on.",
    res:  "Elastic Security & OpenSearch docs (🆓) | AWS CloudTrail / GCP Audit Logs docs (🆓) | Splunk fundamentals (🆓 tier)" },

  // ─── P4 ─ Cryptography & Identity ─
  { id: "CRYPTO", phase: "P4", row: 0, label: "Applied cryptography",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["PY"],
    desc: "Symmetric/asymmetric primitives, hashing, AEAD, signatures and the cardinal rule: use vetted libraries, never roll your own.",
    res:  "Serious Cryptography, Aumasson (💰) | Cryptopals challenges (🆓) | Dan Boneh, Crypto I, Coursera (🆓 audit)" },
  { id: "PKI", phase: "P4", row: 1, label: "PKI, TLS & certificate management",
    priority: "critical", kind: "branch", tracks: ["cloudsec", "appsec"], prereqs: ["CRYPTO", "NET"],
    desc: "Certificate chains, TLS configuration, mTLS, ACME automation and the operational pain of rotation and revocation.",
    res:  "Bulletproof TLS and PKI, Ristić (💰) | Let's Encrypt / ACME docs (🆓) | SSL Labs test & guides (🆓)" },
  { id: "IDENTITY", phase: "P4", row: 2, label: "Identity federation (OAuth/OIDC/SAML)",
    priority: "critical", kind: "branch", tracks: ["appsec", "cloudsec"], prereqs: ["AUTHZ", "CRYPTO"],
    desc: "Delegated authorization and single sign-on done right: flows, token validation, scopes, and the classic implementation traps.",
    res:  "OAuth 2 in Action, Richer & Sanso (💰) | oauth.net & OpenID Connect specs (🆓) | Keycloak docs (🆓)" },
  { id: "PQC", phase: "P4", row: 3, label: "Post-quantum cryptography",
    priority: "desirable", kind: "branch", tracks: ["cloudsec"], prereqs: ["CRYPTO", "PKI"],
    desc: "NIST PQC (ML-KEM/ML-DSA), hybrid deployment, and inventorying crypto so 'harvest-now-decrypt-later' doesn't strand you.",
    res:  "NIST FIPS 203/204/205 (🆓) | Open Quantum Safe / liboqs (🆓) | Cloudflare PQC blog series (🆓)" },
  { id: "KEYMGMT", phase: "P4", row: 4, label: "Key management & HSM/KMS",
    priority: "desirable", kind: "branch", tracks: ["cloudsec"], prereqs: ["CRYPTO", "SECRETS"],
    desc: "Key lifecycle, envelope encryption, HSMs and cloud KMS, and enforcing separation of duties over key material.",
    res:  "Cloud KMS docs, AWS/Azure/GCP (🆓) | NIST SP 800-57 key management (🆓) | PKCS#11 / HSM primers (🆓)" },

  // ─── P5 ─ AI/ML Security (differentiator) ─
  { id: "AIML_BASICS", phase: "P5", row: 0, label: "ML / LLM systems literacy",
    priority: "critical", kind: "branch", tracks: ["aisec"], prereqs: ["PY"],
    desc: "How models train, infer, and get deployed: embeddings, RAG, fine-tuning and agents, enough to secure what you understand.",
    res:  "DeepLearning.AI short courses (🆓) | Hands-On Large Language Models, Alammar & Grootendorst (💰) | Anthropic & OpenAI docs (🆓)" },
  { id: "LLM_TOP10", phase: "P5", row: 1, label: "OWASP LLM Top 10 & prompt injection",
    priority: "critical", kind: "branch", tracks: ["aisec"], prereqs: ["OWASP", "AIML_BASICS"],
    desc: "Direct and indirect prompt injection, insecure output handling, data leakage: the vulnerability canon for LLM apps.",
    res:  "OWASP Top 10 for LLM Applications (🆓) | Lakera Gandalf & prompt-injection primers (🆓) | Simon Willison's writing (🆓)" },
  { id: "AGENT_SEC", phase: "P5", row: 2, label: "Agent & tool-use security",
    priority: "critical", kind: "branch", tracks: ["aisec"], prereqs: ["LLM_TOP10", "AUTHZ"],
    desc: "Scoping tools/MCP, sandboxing, human-in-the-loop, and the confused-deputy risks when a model can take real actions.",
    res:  "OWASP Agentic Security Initiative (🆓) | Anthropic MCP & tool-use docs (🆓) | Google/Microsoft agent security guidance (🆓)" },
  { id: "AICODE_AUDIT", phase: "P5", row: 3, label: "AI-generated code auditing",
    priority: "critical", kind: "branch", tracks: ["aisec", "appsec"], prereqs: ["SECCODE", "SAST"],
    desc: "Reviewing model-authored code for hallucinated packages, insecure defaults and license/IP risk at the volume AI now produces.",
    res:  "GitHub Copilot & Claude Code security docs (🆓) | Semgrep AI-code rules (🆓) | 'slopsquatting' / hallucinated-dependency research (🆓)" },
  { id: "MODEL_SUPPLY", phase: "P5", row: 4, label: "Model & data supply-chain security",
    priority: "critical", kind: "branch", tracks: ["aisec", "devsecops"], prereqs: ["SUPPLY", "AIML_BASICS"],
    desc: "Unsafe model formats (pickle), poisoned datasets and weights, model provenance and signing across the ML pipeline.",
    res:  "safetensors & model-scanning tools (🆓) | Hugging Face security docs (🆓) | NIST/MITRE data-poisoning literature (🆓)" },
  { id: "ADV_ML", phase: "P5", row: 5, label: "Adversarial ML & model robustness",
    priority: "desirable", kind: "branch", tracks: ["aisec"], prereqs: ["AIML_BASICS"],
    desc: "Evasion, extraction, membership inference and backdoors: the classical adversarial-ML threats beyond prompt injection.",
    res:  "MITRE ATLAS (🆓) | Adversarial Robustness Toolbox, IBM ART (🆓) | NIST AI 100-2 adversarial ML taxonomy (🆓)" },
  { id: "PRIVACY", phase: "P5", row: 6, label: "Data privacy & PETs",
    priority: "desirable", kind: "branch", tracks: ["aisec", "grc"], prereqs: ["CRYPTO", "AIML_BASICS"],
    desc: "Differential privacy, federated learning, anonymization and the privacy-enhancing tech that governs training on real data.",
    res:  "The Algorithmic Foundations of DP, Dwork & Roth (🆓) | OpenMined & Opacus tutorials (🆓) | NIST privacy framework (🆓)" },
  { id: "REDTEAM_AI", phase: "P5", row: 7, label: "AI red-teaming & security evals",
    priority: "desirable", kind: "branch", tracks: ["aisec"], prereqs: ["LLM_TOP10", "APPSEC_TEST"],
    desc: "Systematic jailbreak/harm probing and building security evals into the CI of an AI product, not just a one-off review.",
    res:  "Microsoft PyRIT (🆓) | NVIDIA garak LLM scanner (🆓) | Anthropic/OpenAI red-teaming writeups (🆓)" },

  // ─── P6 ─ Detection, Response & Assurance ─
  { id: "DETECT", phase: "P6", row: 0, label: "Detection engineering & threat hunting",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["LOGGING"],
    desc: "Writing detections as code (Sigma), mapping coverage to ATT&CK, and hunting for the activity the alerts miss.",
    res:  "Sigma rules project (🆓) | MITRE ATT&CK (🆓) | The DFIR Report & detection.fyi (🆓)" },
  { id: "IR", phase: "P6", row: 1, label: "Incident response & forensics",
    priority: "critical", kind: "branch", tracks: ["cloudsec", "appsec"], prereqs: ["DETECT"],
    desc: "The IR lifecycle, evidence preservation, cloud/host forensics and blameless post-incident review.",
    res:  "NIST SP 800-61 (🆓) | Blue Team Handbook, Murdoch (💰) | TheHive & Velociraptor (🆓)" },
  { id: "THREATINTEL", phase: "P6", row: 2, label: "Threat intel & MITRE ATT&CK",
    priority: "desirable", kind: "branch", tracks: ["cloudsec"], prereqs: ["DETECT"],
    desc: "Turning IOCs and adversary TTPs into prioritized defense; the pyramid of pain and intelligence-driven detection.",
    res:  "MITRE ATT&CK & ATT&CK Navigator (🆓) | MISP threat-intel platform (🆓) | The Pyramid of Pain, Bianco (🆓)" },
  { id: "VULN", phase: "P6", row: 3, label: "Vulnerability management program",
    priority: "desirable", kind: "branch", tracks: ["devsecops", "grc"], prereqs: ["DEPMGMT"],
    desc: "Standing up scanning, SLAs, risk-based prioritization and metrics: the unglamorous program that prevents most breaches.",
    res:  "CISA vuln-management guidance (🆓) | FIRST CVSS & EPSS (🆓) | Nuclei & OpenVAS scanners (🆓)" },

  // ─── P7 ─ Governance, Risk & Compliance ─
  { id: "GRC_FUND", phase: "P7", row: 0, label: "Security governance & risk",
    priority: "critical", kind: "branch", tracks: ["grc"], prereqs: ["THREAT"],
    desc: "Risk assessment, control frameworks (NIST CSF, ISO 27001) and translating security into decisions leadership will fund.",
    res:  "NIST Cybersecurity Framework 2.0 (🆓) | ISO/IEC 27001 overview (🆓) | CIS Controls v8 (🆓)" },
  { id: "AI_GOV", phase: "P7", row: 1, label: "AI governance & assurance",
    priority: "critical", kind: "branch", tracks: ["grc", "aisec"], prereqs: ["GRC_FUND", "LLM_TOP10"],
    desc: "Operationalizing the EU AI Act, NIST AI RMF and ISO/IEC 42001 into model cards, risk tiers and audit evidence.",
    res:  "NIST AI Risk Management Framework + GenAI profile (🆓) | EU AI Act text & timelines (🆓) | ISO/IEC 42001 overview (🆓)" },
  { id: "COMPLIANCE", phase: "P7", row: 2, label: "Compliance & audit",
    priority: "desirable", kind: "branch", tracks: ["grc"], prereqs: ["GRC_FUND"],
    desc: "SOC 2, PCI-DSS, GDPR and Chile's Law 21.719: evidence collection, control mapping and surviving an external audit.",
    res:  "AICPA SOC 2 & PCI-DSS quick refs (🆓) | GDPR + Chile Law 21.719 primers (🆓) | OpenControl / compliance-as-code (🆓)" },
  { id: "SECURE_SDLC", phase: "P7", row: 3, label: "Secure SDLC & program design",
    priority: "critical", kind: "branch", tracks: ["grc", "devsecops"], prereqs: ["SECCODE", "CICD", "GRC_FUND"],
    desc: "Embedding security across design→deploy: maturity models, security champions, and gates that don't grind delivery to a halt.",
    res:  "OWASP SAMM & BSIMM (🆓) | Microsoft SDL (🆓) | Building Secure & Reliable Systems, Google/O'Reilly (🆓)" },

  // ─── P8 ─ Frontier & Leadership ─
  { id: "FORMAL", phase: "P8", row: 0, label: "Formal methods & verification",
    priority: "frontier", kind: "branch", tracks: ["appsec"], prereqs: ["SECCODE"],
    desc: "Proving properties instead of testing for them: model checking, TLA+ and verified components for the highest-assurance systems.",
    res:  "Learn TLA+, Wayne (🆓) | Software Foundations, Pierce (🆓) | seL4 verified-kernel papers (🆓)" },
  { id: "CONFIDENTIAL", phase: "P8", row: 1, label: "Confidential computing & TEEs",
    priority: "frontier", kind: "branch", tracks: ["cloudsec"], prereqs: ["CRYPTO", "CLOUDSEC"],
    desc: "Trusted execution environments, remote attestation and encrypted-in-use data: protecting workloads even from the host.",
    res:  "Confidential Computing Consortium docs (🆓) | Intel SGX / AMD SEV / AWS Nitro docs (🆓) | Enarx & attestation primers (🆓)" },
  { id: "AISEC_RESEARCH", phase: "P8", row: 2, label: "AI security research frontier",
    priority: "frontier", kind: "branch", tracks: ["aisec"], prereqs: ["ADV_ML", "REDTEAM_AI"],
    desc: "The moving edge: agentic-system exploits, interpretability for defense, alignment-adjacent security and novel jailbreak classes.",
    res:  "arXiv cs.CR + cs.AI (🆓) | Anthropic & Google DeepMind safety research (🆓) | AI Village / DEF CON red-team writeups (🆓)" },
  { id: "LEAD", phase: "P8", row: 3, label: "Technical leadership",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["SECURE_SDLC"],
    desc: "Influence without ownership, risk communication to executives, threat-briefing writing and building a security culture.",
    res:  "The Manager's Path, Fournier (💰) | Google Technical Writing (🆓) | CISA & sector CISO playbooks (🆓)" },
  { id: "ARCH", phase: "P8", row: 4, label: "Security architecture",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["NETSEC", "IDENTITY", "SECURE_SDLC"],
    desc: "Designing defense-in-depth across identity, network, data and application layers: the capstone role this whole path builds toward.",
    res:  "Building Secure & Reliable Systems, Google (🆓) | SABSA & reference architectures (🆓) | AWS/Azure security reference architectures (🆓)" },
];

export default {
  id: "ai-security",
  name: "AI Security & Trustworthy Systems",
  srLabel: "AI Security curriculum grid",
  phases: PHASES,
  tracks: TRACKS,
  courses: COURSES,
};
