// Curriculum data for the AI Security & Trustworthy Systems path.
//
// This module holds data only. It is rendered by
// preview-app/src/components/CurriculumGraph.jsx, which owns all the drawing
// logic shared by every career path.
//
// Eight phases (P0..P7), each about a quarter of study, and four
// specialization tracks. Every track takes 2 to 5 courses in every phase.
//
// Course fields:
//   id        short stable key, shown on the node
//   phase     which phase column the node sits in
//   row       row within that column; must be 0..n-1 with no gaps or repeats
//   priority  critical | desirable | frontier
//   kind      spine (every track) | branch (chosen track only) | elective
//   tracks    ["all"] for spine nodes, otherwise the track ids that need it
//   prereqs   ids of the nodes that must come first
//   desc      one or two sentences shown in the detail panel
//   res       recommended resources, best match first, separated by "|"

// Phases are drawn left to right in the order listed here.
export const PHASES = [
  { id: "P0", label: "Foundations", subtitle: "Systems, networks & threat modeling", color: "#94a3b8" },
  { id: "P1", label: "Phase 1", subtitle: "Web security, secure code & ML literacy", color: "#ef4444" },
  { id: "P2", label: "Phase 2", subtitle: "LLM risks, pipelines & cloud basics", color: "#f97316" },
  { id: "P3", label: "Phase 3", subtitle: "Cryptography, attack practice & supply chain", color: "#f59e0b" },
  { id: "P4", label: "Phase 4", subtitle: "Identity, keys & dependencies", color: "#10b981" },
  { id: "P5", label: "Phase 5", subtitle: "Risk, AI assurance & detection", color: "#8b5cf6" },
  { id: "P6", label: "Phase 6", subtitle: "Security programs, governance & response", color: "#06b6d4" },
  { id: "P7", label: "Phase 7", subtitle: "Architecture, frontier & leadership", color: "#ec4899" },
];

// Specialization tracks. Node stripes and the filter buttons are coloured
// from this map, and the counts on the page are derived from its size.
export const TRACKS = {
  appsec:    { color: "#ef4444", label: "Application security", short: "AppSec" },
  devsecops: { color: "#f97316", label: "DevSecOps & supply chain", short: "DevSecOps" },
  cloudsec:  { color: "#0ea5e9", label: "Cloud & infra security", short: "Cloud" },
  aisec:     { color: "#8b5cf6", label: "AI security & governance", short: "AI & governance" },
};

export const COURSES = [
  // ─── P0 ─ Foundations: Systems, networks & threat modeling ─
  { id: "LINUX", phase: "P0", row: 0, label: "Linux & CLI",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Shell fluency, processes, permissions, systemd, packet basics: the substrate every attack and defense runs on.",
    res:  "Linux Journey (free) | MIT Missing Semester (free) | OverTheWire Bandit wargame (free)" },
  { id: "PY", phase: "P0", row: 1, label: "Python",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Scripting tooling, parsing, HTTP clients, and glue for scanners and CI checks: the security engineer's default language.",
    res:  "Automate the Boring Stuff (free) | Black Hat Python, Seitz (paid) | requests / httpx docs (free)" },
  { id: "NET", phase: "P0", row: 2, label: "Networking & protocols",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "TCP/IP, DNS, TLS handshake, HTTP semantics, proxies and NAT: you cannot secure traffic you cannot read.",
    res:  "Computer Networking: A Top-Down Approach, Kurose & Ross (paid) | Wireshark docs & captures (free) | Cloudflare Learning Center (free)" },
  { id: "WEB", phase: "P0", row: 3, label: "Web platform & HTTP",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["NET"],
    desc: "Browsers, cookies, CORS, same-origin policy, the request/response lifecycle: the attack surface most security careers touch.",
    res:  "MDN Web Docs (free) | PortSwigger Web Security Academy (free) | web.dev security (free)" },
  { id: "THREAT", phase: "P0", row: 4, label: "Security fundamentals & threat modeling",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "CIA triad, trust boundaries, attacker goals, and STRIDE/attack-tree threat modeling: how to reason about risk before writing a control.",
    res:  "Threat Modeling, Shostack (paid) | OWASP Threat Modeling Cheat Sheet (free) | CompTIA Security+ objectives (free)" },
  { id: "GO", phase: "P0", row: 5, label: "Go / systems programming",
    priority: "desirable", kind: "elective", tracks: ["devsecops", "cloudsec"], prereqs: [],
    desc: "The language of cloud-native and security tooling (Kubernetes, Trivy, Terraform providers): a high-leverage second language.",
    res:  "A Tour of Go (free) | Go by Example (free) | The Go Programming Language, Donovan & Kernighan (paid)" },

  // ─── P1 ─ Phase 1: Web security, secure code & ML literacy ─
  { id: "OWASP", phase: "P1", row: 0, label: "OWASP Top 10 & web vulns",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["WEB", "THREAT"],
    desc: "Injection, broken access control, SSRF, XSS, deserialization: the canonical vulnerability classes, hands-on in a lab.",
    res:  "OWASP Top 10 (free) | PortSwigger Web Security Academy labs (free) | PentesterLab (paid, with a free tier)" },
  { id: "SECCODE", phase: "P1", row: 1, label: "Secure coding & code review",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["PY", "OWASP"],
    desc: "Input validation, output encoding, safe defaults, and reviewing a diff for the vulnerability the linter missed.",
    res:  "OWASP Cheat Sheet Series (free) | OWASP ASVS (free) | Secure by Design, Johnsson et al. (paid)" },
  { id: "AUTHZ", phase: "P1", row: 2, label: "AuthN/AuthZ & session security",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["WEB"],
    desc: "Password storage, session tokens, MFA, RBAC/ABAC, and the access-control bugs that top every breach report. Every track enforces access control somewhere: in the app, the pipeline, the cloud account or an agent's tools.",
    res:  "OWASP Authentication & Session Cheat Sheets (free) | PortSwigger access control labs (free) | NIST SP 800-63B (free)" },
  { id: "AIML_BASICS", phase: "P1", row: 3, label: "ML / LLM systems literacy",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["PY"],
    desc: "How models train, infer, and get deployed: embeddings, RAG, fine-tuning and agents, enough to secure what you understand. It sits in the spine because every track on this path ends up securing AI-enabled systems.",
    res:  "DeepLearning.AI short courses (free) | Hands-On Large Language Models, Alammar & Grootendorst (paid) | Anthropic & OpenAI docs (free)" },

  // ─── P2 ─ Phase 2: LLM risks, pipelines & cloud basics ─
  { id: "LLM_TOP10", phase: "P2", row: 0, label: "OWASP LLM Top 10 & prompt injection",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["OWASP", "AIML_BASICS"],
    desc: "Direct and indirect prompt injection, insecure output handling, data leakage: the vulnerability canon for LLM apps, and the AI counterpart of the OWASP Top 10 that every track needs.",
    res:  "OWASP GenAI Security Project: LLM Top 10 2026 (free) | Lakera Gandalf: Agent Breaker & prompt-injection primers (free) | Simon Willison's writing (free)" },
  { id: "SAST", phase: "P2", row: 1, label: "SAST / DAST & fuzzing",
    priority: "critical", kind: "branch", tracks: ["appsec", "devsecops", "aisec"], prereqs: ["SECCODE"],
    desc: "Static/dynamic analysis, semantic queries and coverage-guided fuzzing: automating the search for bugs at scale.",
    res:  "Semgrep & CodeQL docs (free) | OWASP ZAP (free) | Google/OSS-Fuzz & libFuzzer docs (free)" },
  { id: "OS", phase: "P2", row: 2, label: "OS internals & memory model",
    priority: "desirable", kind: "branch", tracks: ["appsec"], prereqs: [],
    desc: "Processes, syscalls, virtual memory, the stack/heap: the mental model behind memory-safety bugs and exploitation.",
    res:  "OSTEP, Operating Systems: Three Easy Pieces (free) | Nand2Tetris (free) | pwn.college (free)" },
  { id: "CICD", phase: "P2", row: 3, label: "CI/CD security",
    priority: "critical", kind: "branch", tracks: ["devsecops", "cloudsec", "aisec"], prereqs: ["SECCODE"],
    desc: "Hardening pipelines against poisoned builds, token theft and privileged runners: the CI system is production, and it is also where cloud credentials, supply-chain provenance and AI security evals live.",
    res:  "OWASP CI/CD Security Top 10 (free) | GitHub Actions security hardening docs (free) | SLSA framework (free)" },
  { id: "CLOUDSEC", phase: "P2", row: 4, label: "Cloud security fundamentals",
    priority: "critical", kind: "branch", tracks: ["appsec", "devsecops", "cloudsec"], prereqs: ["NET", "THREAT"],
    desc: "The shared-responsibility model, the well-architected security pillar, and the primitives across AWS, Azure and GCP: the ground cloud engineers, pipeline owners and AppSec engineers threat-modeling cloud apps all stand on.",
    res:  "AWS/Azure/GCP well-architected security docs (free) | CIS Benchmarks (free) | flAWS & CloudGoat labs (free)" },
  { id: "IAM", phase: "P2", row: 5, label: "Cloud IAM & least privilege",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["CLOUDSEC", "AUTHZ"],
    desc: "Policies, roles, federation, privilege-escalation paths and right-sizing entitlements: cloud breaches are IAM breaches.",
    res:  "AWS IAM & Azure Entra docs (free) | Cloud IAM privilege-escalation research, Rhino Security (free) | Cloudsplaining & pathfinding.cloud (free), why: PMapper has gone unmaintained" },

  // ─── P3 ─ Phase 3: Cryptography, attack practice & supply chain ─
  { id: "CRYPTO", phase: "P3", row: 0, label: "Applied cryptography",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["PY"],
    desc: "Symmetric/asymmetric primitives, hashing, AEAD, signatures and the cardinal rule: use vetted libraries, never roll your own.",
    res:  "Serious Cryptography, Aumasson (paid) | Cryptopals challenges (free) | Dan Boneh, Crypto I, Coursera (free to audit)" },
  { id: "APPSEC_TEST", phase: "P3", row: 1, label: "Pentesting & exploitation basics",
    priority: "desirable", kind: "branch", tracks: ["appsec"], prereqs: ["OWASP", "OS"],
    desc: "Recon, exploitation, and privilege escalation on deliberately vulnerable targets: thinking like the attacker you defend against.",
    res:  "TryHackMe & Hack The Box (paid, with a free tier) | HackTricks (free) | PEN-200/OSCP, OffSec (paid)" },
  { id: "API", phase: "P3", row: 2, label: "API & mobile security",
    priority: "desirable", kind: "branch", tracks: ["appsec"], prereqs: ["OWASP", "AUTHZ"],
    desc: "REST/GraphQL abuse, broken object-level authorization (BOLA), rate limiting, and mobile client/transport pitfalls.",
    res:  "OWASP API Security Top 10 (free) | OWASP MASVS/MASTG (free) | PortSwigger GraphQL & API labs (free)" },
  { id: "AGENT_SEC", phase: "P3", row: 3, label: "Agent & tool-use security",
    priority: "critical", kind: "branch", tracks: ["appsec", "aisec"], prereqs: ["LLM_TOP10", "AUTHZ"],
    desc: "Scoping tools/MCP, sandboxing, human-in-the-loop, and the confused-deputy risks when a model can take real actions.",
    res:  "OWASP Agentic Security Initiative: Securing Agentic Applications guide (free) | Anthropic MCP & tool-use docs (free) | Google/Microsoft agent security guidance (free)" },
  { id: "ADV_ML", phase: "P3", row: 4, label: "Adversarial ML & model robustness",
    priority: "desirable", kind: "branch", tracks: ["aisec"], prereqs: ["AIML_BASICS"],
    desc: "Evasion, extraction, membership inference and backdoors: the classical adversarial-ML threats beyond prompt injection.",
    res:  "MITRE ATLAS (free) | Adversarial Robustness Toolbox, IBM ART (free) | NIST AI 100-2 E2025 adversarial ML taxonomy (free)" },
  { id: "SUPPLY", phase: "P3", row: 5, label: "Software supply chain & SBOM",
    priority: "critical", kind: "branch", tracks: ["devsecops", "aisec"], prereqs: ["CICD"],
    desc: "Artifact signing, provenance, SBOMs and reproducible builds: defending against the dependency and build-system attacks now dominating headlines.",
    res:  "SLSA & in-toto (free) | Sigstore / cosign (free) | CycloneDX & SPDX SBOM specs (free)" },
  { id: "SECRETS", phase: "P3", row: 6, label: "Secrets management",
    priority: "critical", kind: "branch", tracks: ["devsecops", "cloudsec"], prereqs: ["CICD"],
    desc: "Vaulting, dynamic/short-lived credentials, secret scanning and rotation: keeping keys out of git and out of memory dumps.",
    res:  "HashiCorp Vault docs (free) | gitleaks & trufflehog (free) | Cloud secrets-manager docs (free)" },
  { id: "IAC", phase: "P3", row: 7, label: "IaC & policy as code",
    priority: "critical", kind: "branch", tracks: ["devsecops", "cloudsec"], prereqs: ["CICD", "CLOUDSEC"],
    desc: "Terraform/OpenTofu security, and codifying guardrails with OPA/Rego and Conftest so misconfig fails the build.",
    res:  "Terraform & OpenTofu docs (free) | Open Policy Agent / Rego (free) | Checkov & Trivy (free), why: tfsec is retired, its checks live in Trivy now" },
  { id: "NETSEC", phase: "P3", row: 8, label: "Network security & zero trust",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["NET", "CLOUDSEC"],
    desc: "Segmentation, VPCs, firewalls, service mesh mTLS and the identity-centric zero-trust model that replaces the perimeter.",
    res:  "NIST SP 800-207 Zero Trust Architecture (free) | BeyondCorp papers, Google (free) | Cloud networking security docs (free)" },

  // ─── P4 ─ Phase 4: Identity, keys & dependencies ─
  { id: "IDENTITY", phase: "P4", row: 0, label: "Identity federation (OAuth/OIDC/SAML)",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["AUTHZ", "CRYPTO"],
    desc: "Delegated authorization and single sign-on done right: flows, token validation, scopes, and the classic implementation traps. Every track meets it: SSO in applications, OIDC federation from CI to cloud, and OAuth-based authorization for agents and MCP servers.",
    res:  "OAuth 2 in Action, Richer & Sanso (paid) | oauth.net & OpenID Connect specs (free) | Keycloak docs (free)" },
  { id: "PKI", phase: "P4", row: 1, label: "PKI, TLS & certificate management",
    priority: "critical", kind: "branch", tracks: ["appsec", "cloudsec"], prereqs: ["CRYPTO", "NET"],
    desc: "Certificate chains, TLS configuration, mTLS, ACME automation and the operational pain of rotation and revocation.",
    res:  "Bulletproof TLS and PKI, Ristić (paid) | Let's Encrypt / ACME docs (free) | SSL Labs test & guides (free)" },
  { id: "KEYMGMT", phase: "P4", row: 2, label: "Key management & HSM/KMS",
    priority: "desirable", kind: "branch", tracks: ["cloudsec"], prereqs: ["CRYPTO", "SECRETS"],
    desc: "Key lifecycle, envelope encryption, HSMs and cloud KMS, and enforcing separation of duties over key material.",
    res:  "Cloud KMS docs, AWS/Azure/GCP (free) | NIST SP 800-57 key management (free) | PKCS#11 / HSM primers (free)" },
  { id: "DEPMGMT", phase: "P4", row: 3, label: "Dependency & vulnerability management",
    priority: "critical", kind: "branch", tracks: ["appsec", "devsecops"], prereqs: ["SAST"],
    desc: "SCA, CVE triage, reachability analysis and prioritization with EPSS/KEV so you patch what actually matters: most application code is third-party, so dependency risk is AppSec's and DevSecOps' problem.",
    res:  "OWASP Dependency-Check & Dependabot (free) | OSV & FIRST EPSS (free) | CISA Known Exploited Vulnerabilities catalog (free)" },
  { id: "MODEL_SUPPLY", phase: "P4", row: 4, label: "Model & data supply-chain security",
    priority: "critical", kind: "branch", tracks: ["devsecops", "aisec"], prereqs: ["SUPPLY", "AIML_BASICS"],
    desc: "Unsafe model formats (pickle), poisoned datasets and weights, model provenance and signing across the ML pipeline.",
    res:  "safetensors & model-scanning tools (free) | Hugging Face security docs (free) | NIST/MITRE data-poisoning literature (free)" },
  { id: "PRIVACY", phase: "P4", row: 5, label: "Data privacy & PETs",
    priority: "desirable", kind: "branch", tracks: ["aisec"], prereqs: ["CRYPTO", "AIML_BASICS"],
    desc: "Differential privacy, federated learning, anonymization and the privacy-enhancing tech that governs training on real data.",
    res:  "The Algorithmic Foundations of DP, Dwork & Roth (free) | OpenMined & Opacus tutorials (free) | NIST privacy framework (free)" },
  { id: "CONTAINER", phase: "P4", row: 6, label: "Container & Kubernetes security",
    priority: "critical", kind: "branch", tracks: ["devsecops", "cloudsec"], prereqs: ["LINUX", "IAC"],
    desc: "Image hardening, rootless containers, admission control, network policy, RBAC and runtime detection in the orchestrator.",
    res:  "Kubernetes security docs & CIS Benchmark (free) | Falco & Trivy (free) | Container Security, Rice (paid)" },

  // ─── P5 ─ Phase 5: Risk, AI assurance & detection ─
  { id: "GRC_FUND", phase: "P5", row: 0, label: "Security governance & risk",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["THREAT"],
    desc: "Risk assessment, control frameworks (NIST CSF, ISO 27001) and translating security into decisions leadership will fund. It is in the spine because architecture and leadership both rest on this risk language.",
    res:  "NIST Cybersecurity Framework 2.0 (free) | ISO/IEC 27001 overview (free) | CIS Controls v8.1 (free)" },
  { id: "AICODE_AUDIT", phase: "P5", row: 1, label: "AI-generated code auditing",
    priority: "critical", kind: "branch", tracks: ["appsec", "devsecops", "aisec"], prereqs: ["SECCODE", "SAST"],
    desc: "Reviewing model-authored code for hallucinated packages, insecure defaults and license/IP risk at the volume AI now produces.",
    res:  "GitHub Copilot & Claude Code security docs (free) | Semgrep AI-code rules (free) | 'slopsquatting' / hallucinated-dependency research (free)" },
  { id: "REDTEAM_AI", phase: "P5", row: 2, label: "AI red-teaming & security evals",
    priority: "desirable", kind: "branch", tracks: ["appsec", "aisec"], prereqs: ["LLM_TOP10", "AGENT_SEC"],
    desc: "Systematic jailbreak/harm probing and building security evals into the CI of an AI product, not just a one-off review.",
    res:  "Microsoft PyRIT (free) | NVIDIA garak LLM scanner (free) | Anthropic/OpenAI red-teaming writeups (free)" },
  { id: "CSPM", phase: "P5", row: 3, label: "CSPM & cloud posture",
    priority: "desirable", kind: "branch", tracks: ["devsecops", "cloudsec"], prereqs: ["CLOUDSEC", "IAC"],
    desc: "Continuous posture scanning, drift detection and misconfiguration remediation across accounts and clouds.",
    res:  "Prowler & ScoutSuite (free) | Steampipe / CloudQuery (free) | CIS cloud benchmarks (free)" },
  { id: "LOGGING", phase: "P5", row: 4, label: "Logging, monitoring & SIEM",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["CLOUDSEC"],
    desc: "Centralized telemetry, audit trails, log integrity and a SIEM that turns events into alerts you can act on.",
    res:  "Elastic Security & OpenSearch docs (free) | AWS CloudTrail / GCP Audit Logs docs (free) | Splunk free training courses (free)" },
  { id: "DETECT", phase: "P5", row: 5, label: "Detection engineering & threat hunting",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["LOGGING"],
    desc: "Writing detections as code (Sigma), mapping coverage to ATT&CK, and hunting for the activity the alerts miss.",
    res:  "Sigma rules project (free) | MITRE ATT&CK (free) | The DFIR Report & detection.fyi (free)" },

  // ─── P6 ─ Phase 6: Security programs, governance & response ─
  { id: "SECURE_SDLC", phase: "P6", row: 0, label: "Secure SDLC & program design",
    priority: "critical", kind: "branch", tracks: ["appsec", "devsecops", "aisec"], prereqs: ["SAST", "GRC_FUND"],
    desc: "Embedding security across design→deploy: maturity models, security champions, and gates that don't grind delivery to a halt.",
    res:  "OWASP SAMM & BSIMM (free) | Microsoft SDL (free) | Building Secure & Reliable Systems, Google/O'Reilly (free)" },
  { id: "VULN", phase: "P6", row: 1, label: "Vulnerability management program",
    priority: "desirable", kind: "branch", tracks: ["appsec", "devsecops"], prereqs: ["DEPMGMT"],
    desc: "Standing up scanning, SLAs, risk-based prioritization and metrics: the unglamorous program that prevents most breaches.",
    res:  "CISA vuln-management guidance (free) | FIRST CVSS & EPSS (free) | Nuclei & OpenVAS scanners (free)" },
  { id: "COMPLIANCE", phase: "P6", row: 2, label: "Compliance & audit",
    priority: "desirable", kind: "branch", tracks: ["aisec"], prereqs: ["GRC_FUND"],
    desc: "SOC 2, PCI-DSS, GDPR and Chile's Law 21.719: evidence collection, control mapping and surviving an external audit.",
    res:  "AICPA SOC 2 & PCI-DSS quick refs (free) | GDPR + Chile Law 21.719 primers (free) | NIST OSCAL compliance-as-code (free), why: it superseded OpenControl as the standard format" },
  { id: "AI_GOV", phase: "P6", row: 3, label: "AI governance & assurance",
    priority: "critical", kind: "branch", tracks: ["aisec"], prereqs: ["GRC_FUND", "LLM_TOP10"],
    desc: "Operationalizing the EU AI Act, NIST AI RMF and ISO/IEC 42001 into model cards, risk tiers and audit evidence.",
    res:  "NIST AI Risk Management Framework + GenAI profile (free) | EU AI Act text & timelines (free) | ISO/IEC 42001 overview (free)" },
  { id: "IR", phase: "P6", row: 4, label: "Incident response & forensics",
    priority: "critical", kind: "branch", tracks: ["cloudsec"], prereqs: ["DETECT"],
    desc: "The IR lifecycle, evidence preservation, cloud/host forensics and blameless post-incident review.",
    res:  "NIST SP 800-61r3 (free) | Blue Team Handbook, Murdoch (paid) | TheHive & Velociraptor (free)" },
  { id: "THREATINTEL", phase: "P6", row: 5, label: "Threat intel & MITRE ATT&CK",
    priority: "desirable", kind: "branch", tracks: ["cloudsec"], prereqs: ["DETECT"],
    desc: "Turning IOCs and adversary TTPs into prioritized defense; the pyramid of pain and intelligence-driven detection.",
    res:  "MITRE ATT&CK & ATT&CK Navigator (free) | MISP threat-intel platform (free) | The Pyramid of Pain, Bianco (free)" },

  // ─── P7 ─ Phase 7: Architecture, frontier & leadership ─
  { id: "ARCH", phase: "P7", row: 0, label: "Security architecture",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["IDENTITY", "LLM_TOP10", "GRC_FUND"],
    desc: "Designing defense-in-depth across identity, network, data, application and AI/agent layers: the capstone role this whole path builds toward.",
    res:  "Building Secure & Reliable Systems, Google (free) | SABSA & reference architectures (free) | AWS/Azure security reference architectures (free)" },
  { id: "LEAD", phase: "P7", row: 1, label: "Technical leadership",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["GRC_FUND"],
    desc: "Influence without ownership, risk communication to executives, threat-briefing writing and building a security culture.",
    res:  "The Manager's Path, Fournier (paid) | Google Technical Writing (free) | CISA & sector CISO playbooks (free)" },
  { id: "FORMAL", phase: "P7", row: 2, label: "Formal methods & verification",
    priority: "frontier", kind: "branch", tracks: ["appsec"], prereqs: ["SECCODE"],
    desc: "Proving properties instead of testing for them: model checking, TLA+ and verified components for the highest-assurance systems.",
    res:  "Learn TLA+, Wayne (free) | Software Foundations, Pierce (free) | seL4 verified-kernel papers (free)" },
  { id: "AISEC_RESEARCH", phase: "P7", row: 3, label: "AI security research frontier",
    priority: "frontier", kind: "branch", tracks: ["aisec"], prereqs: ["ADV_ML", "REDTEAM_AI"],
    desc: "The moving edge: agentic-system exploits, interpretability for defense, alignment-adjacent security and novel jailbreak classes.",
    res:  "arXiv cs.CR + cs.AI (free) | Anthropic & Google DeepMind safety research (free) | AI Village / DEF CON red-team writeups (free)" },
  { id: "CONFIDENTIAL", phase: "P7", row: 4, label: "Confidential computing & TEEs",
    priority: "frontier", kind: "branch", tracks: ["cloudsec"], prereqs: ["CRYPTO", "CLOUDSEC"],
    desc: "Trusted execution environments, remote attestation and encrypted-in-use data: protecting workloads even from the host.",
    res:  "Confidential Computing Consortium docs (free) | Intel SGX / AMD SEV / AWS Nitro docs (free) | Enarx & attestation primers (free)" },
  { id: "PQC", phase: "P7", row: 5, label: "Post-quantum cryptography",
    priority: "desirable", kind: "branch", tracks: ["cloudsec"], prereqs: ["CRYPTO", "PKI"],
    desc: "NIST PQC (ML-KEM/ML-DSA), hybrid deployment, and inventorying crypto so 'harvest-now-decrypt-later' doesn't strand you.",
    res:  "NIST FIPS 203/204/205 (free) | Open Quantum Safe / liboqs (free) | Cloudflare PQC blog series (free)" },
];

export default {
  id: "ai-security",
  name: "AI Security & Trustworthy Systems",
  srLabel: "AI Security curriculum grid",
  phases: PHASES,
  tracks: TRACKS,
  courses: COURSES,
};
