// Curriculum data for the Control Systems & Robotics path.
//
// This module holds data only. It is rendered by
// preview-app/src/components/CurriculumGraph.jsx, which owns all the drawing
// logic shared by the four career paths.
//
// Course fields:
//   id        short stable key, shown on the node
//   phase     which phase column the node sits in
//   row       row within that column; must be 0..n-1 with no gaps or repeats
//   priority  critical | desirable | frontier
//   kind      spine (every track) | branch (chosen track only) | elective
//   tracks    ["all"] for spine nodes, otherwise the track ids that need it
//   prereqs   ids of the nodes that must come first
//   desc      one or two sentences shown in the detail panel
//   res       recommended resources, separated by "|"

// Phases are drawn left to right in the order listed here.
export const PHASES = [
  { id: "P0", label: "Foundations", subtitle: "Math & programming", color: "#94a3b8" },
  { id: "P1", label: "Phase 1", subtitle: "Signals & classical control", color: "#22d3ee" },
  { id: "P2", label: "Phase 2", subtitle: "Modeling & state-space", color: "#06b6d4" },
  { id: "P3", label: "Phase 3", subtitle: "Estimation & filtering", color: "#0ea5e9" },
  { id: "P4", label: "Phase 4", subtitle: "Optimal & predictive control", color: "#6366f1" },
  { id: "P5", label: "Phase 5", subtitle: "Nonlinear & robust control", color: "#8b5cf6" },
  { id: "P6", label: "Phase 6", subtitle: "Real-time & integration", color: "#14b8a6" },
  { id: "P7", label: "Phase 7", subtitle: "Domain & systems", color: "#f59e0b" },
  { id: "P8", label: "Phase 8", subtitle: "Frontier & leadership", color: "#fb923c" },
];

// Specialization tracks. Node stripes and the filter buttons are coloured
// from this map, and the counts on the page are derived from its size.
export const TRACKS = {
  industrial:{ color: "#d97706", label: "Industrial & process control", short: "Industrial" },
  robotics:  { color: "#059669", label: "Robotics & motion control", short: "Robotics" },
  aerospace: { color: "#2563eb", label: "Aerospace GNC", short: "Aerospace" },
  automotive:{ color: "#dc2626", label: "Autonomous vehicles", short: "Vehicles" },
  estimation:{ color: "#7c3aed", label: "Estimation & navigation", short: "Estimation" },
};

export const COURSES = [
  // ─── P0 ─ Math & programming ─
  { id: "LINUX", phase: "P0", row: 0, label: "Linux & CLI",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Terminal, bash, file systems, permissions, SSH. The base layer for embedded targets, simulators and robotics middleware.",
    res:  "Linux Journey (free) | MIT Missing Semester (free) | Coursera: Unix Workbench \u2014 JHU (audit)" },
  { id: "PY", phase: "P0", row: 1, label: "Python",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Core scripting for control: NumPy, SciPy, Matplotlib and the python-control / CasADi ecosystem.",
    res:  "Python for Everybody \u2014 UMich (audit) | Automate the Boring Stuff (free) | python-control docs (free)" },
  { id: "CPP", phase: "P0", row: 2, label: "C++",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Pointers, memory, RAII, STL and real-time patterns. The language of embedded controllers, ROS2 and autopilots.",
    res:  "learncpp.com (free) | A Tour of C++ \u2014 Stroustrup (~$40) | Coursera: C++ for C Programmers \u2014 UCSC (audit)" },
  { id: "MATLAB", phase: "P0", row: 3, label: "MATLAB & Simulink",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "MATLAB, Simulink, Stateflow and the Control System Toolbox: the industry-standard environment for modeling dynamic systems, designing and tuning controllers, simulating closed loops, and (via Simulink/Embedded Coder) generating embedded code.",
    res:  "MathWorks MATLAB & Simulink Onramps (free) | Control Design Onramp with Simulink (free) | Stateflow Onramp (free) | MATLAB Tech Talks \u2014 Controls (free YT) | Coursera: Intro to Programming with MATLAB \u2014 Vanderbilt (audit)" },
  { id: "LA", phase: "P0", row: 4, label: "Linear algebra",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Vectors, matrices, eigenvalues, SVD. The backbone of state-space control, estimation and optimization.",
    res:  "3Blue1Brown: Essence of Linear Algebra (free YT) | MIT 18.06 \u2014 Strang (free) | Khan Academy (free)" },
  { id: "CALC", phase: "P0", row: 5, label: "Calculus",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Derivatives, integrals, chain rule, gradients. Prerequisite for dynamics, optimization and every control law.",
    res:  "3Blue1Brown: Essence of Calculus (free YT) | Khan Academy (free) | MIT 18.01 (free)" },
  { id: "ODE", phase: "P0", row: 6, label: "Differential equations",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CALC"],
    desc: "First and second-order ODEs, Laplace transforms, and linear systems of ODEs (eigenvalue/matrix-exponential solutions). The math describing how dynamic systems evolve in time.",
    res:  "MIT 18.03SC Differential Equations OCW (free) | 3Blue1Brown Differential Equations (free YT) | Steve Brunton Differential Equations and Dynamical Systems (free YT) | Boyce & DiPrima Elementary Differential Equations (~$80 digital/rental)" },
  { id: "PROB", phase: "P0", row: 7, label: "Probability & statistics",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Probability, distributions, random variables and estimation-theory basics \u2014 the foundation for filtering and stochastic control.",
    res:  "Statistics with Python \u2014 UMich (audit) | Think Stats (free) | Khan Academy (free)" },
  { id: "GIT", phase: "P0", row: 8, label: "Git & version control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Repos, branches, PRs, CI workflows. Version control for models, controllers and embedded firmware.",
    res:  "git-scm.com tutorial (free) | GitHub Skills (free) | Coursera: Version Control \u2014 Meta (audit)" },
  // ─── P1 ─ Signals & classical control ─
  { id: "SIGSYS", phase: "P1", row: 0, label: "Signals & systems",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CALC", "ODE", "LA"],
    desc: "Continuous and discrete signals, convolution, Fourier/Laplace/Z transforms, LTI systems and transfer functions, frequency response and sampling. The mathematical language underlying all feedback control.",
    res:  "MIT RES.6-007 Oppenheim lectures (free) | Steve Brunton Fourier Analysis (free YT) | Oppenheim & Willsky Signals and Systems (~$65 used) | Lathi & Green Linear Systems and Signals (~$100 used)" },
  { id: "CLASSIC", phase: "P1", row: 1, label: "Classical control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["SIGSYS"],
    desc: "PID, root locus, Bode/Nyquist, lead-lag compensation, loop shaping, and gain/phase stability margins. Single-loop, single-input/single-output feedback design in continuous time.",
    res:  "Brian Douglas Control System Lectures (free YT) | MATLAB Tech Talks: Understanding Control Systems (free YT) | Astrom & Murray, Feedback Systems 2e, fbswiki.org (free) | Nise, Control Systems Engineering 8e (~$60-80 used/intl) | Ogata, Modern Control Engineering 5e (~$70 used)" },
  { id: "DIGITAL", phase: "P1", row: 2, label: "Digital control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CLASSIC"],
    desc: "Discretization (ZOH, Tustin, matched pole-zero), z-domain design, sampling and aliasing, anti-alias filtering, and implementing fixed-rate controllers in code with attention to delay and quantization.",
    res:  "Brian Douglas Discrete control series (free YT) | Franklin, Powell & Workman Digital Control of Dynamic Systems, author-hosted Ellis-Kagle/SC Solutions PDF (free) | Astrom & Wittenmark Computer-Controlled Systems, Dover 3rd ed. (~$40) | MathWorks Control Systems in Practice: 4 Ways to Implement a Transfer Function in Code (free YT)" },
  // ─── P2 ─ Modeling & state-space ─
  { id: "STSP", phase: "P2", row: 0, label: "State-space control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CLASSIC", "LA"],
    desc: "State-space models, controllability and observability, pole placement via state feedback, modal analysis, and Luenberger observers. Separation principle and multivariable (MIMO) design.",
    res:  "Steve Brunton Control Bootcamp (free YT) | Stanford EE263 Boyd, Linear Dynamical Systems (free) | MATLAB State Space Tech Talks, Brian Douglas (free YT) | Friedland, Control System Design (Dover) (~$35) | Hespanha, Linear Systems Theory 2e (Princeton) (~$105)" },
  { id: "DYN", phase: "P2", row: 1, label: "Dynamics & modeling",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["ODE", "LA"],
    desc: "Newtonian and Lagrangian mechanics, rigid-body kinematics and dynamics. Derive equations of motion for plants and manipulators; linearize about operating points to get state-space models for control design.",
    res:  "MIT OCW 2.003J Dynamics & Control I (free) | Lynch & Park Modern Robotics ch. 8 preprint (free) | Modern Robotics dynamics lectures (free YT) | Taylor Classical Mechanics (~$160) | Featherstone Rigid Body Dynamics Algorithms (~$160+)" },
  { id: "ROBKIN", phase: "P2", row: 2, label: "Robot kinematics & dynamics",
    priority: "critical", kind: "branch", tracks: ["robotics"], prereqs: ["DYN", "LA"],
    desc: "Forward and inverse kinematics, DH parameters, screw theory and product of exponentials, the Jacobian, and rigid-body manipulator dynamics (Newton-Euler, Euler-Lagrange). The model of a robot arm.",
    res:  "Modern Robotics \u2014 Lynch & Park, free preprint + videos (free) | Modern Robotics specialization, Coursera (audit) | QUT Robot Academy \u2014 Peter Corke (free) | Spong, Hutchinson & Vidyasagar Robot Modeling and Control (~$140) | Siciliano et al. Robotics: Modelling, Planning and Control, softcover (~$90)" },
  { id: "SYSID", phase: "P2", row: 3, label: "System identification",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["STSP", "PROB"],
    desc: "Building dynamic models from input/output data: least-squares, ARX/ARMAX prediction-error methods, subspace identification, frequency-response estimation, grey-box fitting, plus excitation design and model validation.",
    res:  "Ljung, System Identification: Theory for the User (~$150) | MATLAB System Identification Toolbox docs (free) | Steve Brunton, Data-Driven Control / System ID (free YT) | J. Schoukens & L. Ljung, Nonlinear System ID Roadmap, arXiv (free) | Pintelon & Schoukens, Frequency Domain Approach (~$165)" },
  { id: "NUM", phase: "P2", row: 4, label: "Numerical methods & simulation",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["LA", "ODE", "PY"],
    desc: "ODE solvers (Runge-Kutta, stiff/implicit methods), numerical linear algebra, integration error and stability. Simulating dynamical systems accurately and fast in Python/SciPy. The compute layer under every controller.",
    res:  "Steve Brunton AMATH301 / Engineering Mathematics (free YT) | MIT OCW 18.330 Numerical Analysis (free) | Scientific Python Lectures (free) | Hairer, Norsett & Wanner Solving ODEs I (~$90) | Numerical Recipes 3rd Ed (~$70 used/new, $125 list)" },
  // ─── P3 ─ Estimation & filtering ─
  { id: "KF", phase: "P3", row: 0, label: "Kalman filtering",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["STSP", "PROB"],
    desc: "The Kalman filter: optimal linear state estimation via the predict/update recursion, covariance propagation, the Kalman gain, the steady-state form, and tuning the process/measurement noise (Q, R).",
    res:  "Roger Labbe \u2014 Kalman and Bayesian Filters in Python (free) | Steve Brunton Control Bootcamp: Kalman Filter (free YT) | MATLAB Tech Talks \"Understanding Kalman Filters\" (free YT) | Cyrill Stachniss Kalman/EKF lectures (free YT) | Dan Simon \u2014 Optimal State Estimation (~$80 used)" },
  { id: "NLEST", phase: "P3", row: 1, label: "Nonlinear estimation (EKF/UKF)",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["KF"],
    desc: "Estimation for nonlinear systems: extended Kalman filter (Jacobian linearization), unscented Kalman filter (sigma points), and particle filters. Process/measurement models, consistency, divergence and tuning.",
    res:  "Roger Labbe \u2014 Kalman and Bayesian Filters in Python (free) | Cyrill Stachniss EKF/UKF/PF lectures (free YT) | Dan Simon \u2014 Optimal State Estimation (~$160) | Thrun, Burgard & Fox \u2014 Probabilistic Robotics (~$105)" },
  { id: "NAV", phase: "P3", row: 2, label: "Navigation & sensor fusion",
    priority: "critical", kind: "branch", tracks: ["estimation", "aerospace", "automotive", "robotics"], prereqs: ["NLEST"],
    desc: "Strapdown inertial navigation, GNSS positioning, IMU mechanization and INS/GNSS fusion (loose/tight coupling) for position, velocity and attitude. Reference frames, error-state EKF, sensor bias modeling.",
    res:  "Paul Groves \u2014 GNSS, Inertial & Multisensor Integrated Navigation (~$170) | Farrell \u2014 Aided Navigation (~$135) | Coursera \"State Estimation & Localization for Self-Driving Cars,\" UToronto (audit) | VectorNav Inertial Navigation Primer (free) | Cyrill Stachniss \u2014 Kalman/EKF & SLAM lectures (free YT)" },
  { id: "SLAM", phase: "P3", row: 3, label: "SLAM",
    priority: "desirable", kind: "branch", tracks: ["robotics", "estimation", "automotive"], prereqs: ["NLEST"],
    desc: "Simultaneous localization and mapping: EKF-SLAM and FastSLAM, pose-graph/factor-graph optimization, loop closure and data association, with visual and LiDAR front-ends.",
    res:  "Cyrill Stachniss SLAM Course (free YT) | Thrun, Burgard & Fox Probabilistic Robotics (~$125) | Cadena et al. Past/Present/Future of SLAM survey, arXiv (free) | GTSAM + Dellaert Factor Graphs hands-on tutorial (free)" },
  { id: "ESTADV", phase: "P3", row: 4, label: "Smoothing & tracking",
    priority: "desirable", kind: "branch", tracks: ["estimation", "automotive"], prereqs: ["NLEST"],
    desc: "Factor-graph batch and fixed-lag smoothing with iSAM2/GTSAM; multi-target tracking and data association (nearest-neighbor, JPDA, MHT) for cluttered sensor streams.",
    res:  "Dellaert & Kaess, Factor Graphs for Robot Perception (free) | GTSAM tutorials, gtsam.org (free) | Stachniss graph-based SLAM lectures (free YT) | Bar-Shalom, Li & Kirubarajan, Estimation with Applications to Tracking and Navigation (~$185)" },
  // ─── P4 ─ Optimal & predictive control ─
  { id: "OPT", phase: "P4", row: 0, label: "Optimization for control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["LA", "NUM"],
    desc: "Convex optimization, LP/QP/NLP, KKT conditions, duality and solver internals (interior-point, active-set, ADMM). The optimization engine under optimal control, MPC and estimation.",
    res:  "Boyd & Vandenberghe Convex Optimization (free) | Stanford EE364a Boyd lectures (free YT) | Nocedal & Wright Numerical Optimization (~$80) | CVXPY docs (free) | OSQP solver docs incl. MPC example (free)" },
  { id: "OPTCTRL", phase: "P4", row: 1, label: "Optimal control (LQR/LQG)",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["STSP", "KF"],
    desc: "LQR, the algebraic Riccati equation, LQG, and the calculus of variations / Pontryagin minimum principle \u2014 optimal feedback for linear (and locally nonlinear) systems.",
    res:  "Steve Brunton Control Bootcamp \u2014 LQR/LQG (free YT) | Stanford EE363 \u2014 Boyd (free) | Anderson & Moore Optimal Control: Linear Quadratic Methods (free) | Kirk Optimal Control Theory (~$35 Dover)" },
  { id: "MPC", phase: "P4", row: 2, label: "Model predictive control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["OPTCTRL", "OPT"],
    desc: "Receding-horizon control under constraints: linear and nonlinear MPC, QP/NLP formulations, terminal cost/set design for stability and recursive feasibility, and real-time embedded solvers (OSQP, acados, CasADi).",
    res:  "Rawlings, Mayne & Diehl MPC: Theory, Computation, Design 2nd ed (free PDF) | Borrelli, Bemporad & Morari Predictive Control for Linear and Hybrid Systems (free PDF) | acados / OSQP / do-mpc docs (free) | MATLAB Understanding MPC Tech Talks (free YT)" },
  { id: "TRAJOPT", phase: "P4", row: 3, label: "Trajectory optimization & planning",
    priority: "desirable", kind: "branch", tracks: ["robotics", "aerospace", "automotive"], prereqs: ["OPT", "OPTCTRL"],
    desc: "Trajectory optimization and motion planning: direct transcription/shooting, direct collocation, iLQR/DDP, sampling-based planners (RRT/PRM), and planning through contact. Maps optimal control onto nonlinear programs.",
    res:  "Tedrake Underactuated Robotics, Ch.10 & 12 (free) | Matthew Kelly, Intro to Trajectory Optimization + OptimTraj (free) | CasADi optimal-control examples (free) | Modern Robotics Course 4: Motion Planning (audit) | LaValle, Planning Algorithms (free)" },
  // ─── P5 ─ Nonlinear & robust control ─
  { id: "NLCTRL", phase: "P5", row: 0, label: "Nonlinear control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["STSP", "ODE"],
    desc: "Lyapunov stability and LaSalle's invariance, feedback linearization, backstepping, sliding-mode and passivity-based control. Stability analysis and constructive design for nonlinear systems beyond local linearization.",
    res:  "Khalil Nonlinear Systems 3rd ed (~$150) | Slotine & Li Applied Nonlinear Control (~$90) | Tedrake Underactuated Robotics + YT (free) | Khalil Nonlinear Control, Pearson (~$95) | MathWorks \"What Is Sliding Mode Control?\" Tech Talk (free YT)" },
  { id: "ROBUST", phase: "P5", row: 1, label: "Robust control",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["STSP", "OPTCTRL"],
    desc: "Designing for plant uncertainty: H-infinity and mixed-sensitivity synthesis, mu-synthesis with D-K iteration, structured/unstructured uncertainty, sensitivity and robustness margins, and multivariable (MIMO) loop shaping.",
    res:  "Skogestad & Postlethwaite, Multivariable Feedback Control (~$70 paperback; free 3-ch sample) | Zhou & Doyle, Essentials of Robust Control (~$90, mostly used) | MathWorks Robust Control video series, Brian Douglas (free YT) | MATLAB Robust Control Toolbox docs (free)" },
  { id: "ADAPT", phase: "P5", row: 2, label: "Adaptive control",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["NLCTRL", "SYSID"],
    desc: "Controllers that tune themselves online: model-reference adaptive control (MRAC), self-tuning regulators, gain scheduling, and L1 adaptive control. Lyapunov-based adaptation laws, parameter convergence, and robustness modifications.",
    res:  "Ioannou & Sun, Robust Adaptive Control (free PDF) | Astrom & Wittenmark, Adaptive Control 2e, Dover (~$33) | Slotine & Li, Applied Nonlinear Control ch.8 (~$85) | Hovakimyan & Cao, L1 Adaptive Control Theory, SIAM (~$103)" },
  { id: "FORCE", phase: "P5", row: 3, label: "Force & impedance control",
    priority: "desirable", kind: "branch", tracks: ["robotics"], prereqs: ["ROBKIN", "NLCTRL"],
    desc: "Interaction control for robots in contact: impedance and admittance control, hybrid force/position control, compliance, and Khatib's operational-space formulation for unified motion and force regulation.",
    res:  "Modern Robotics Ch.11 Force Control (free YT) | Siciliano et al. Robotics: Modelling, Planning and Control, Ch.9 (~$90) | Hogan, Impedance Control Part I\u2014Theory 1985 (free) | Khatib, Operational Space Formulation 1987 (free)" },
  // ─── P6 ─ Real-time & integration ─
  { id: "EMBED", phase: "P6", row: 0, label: "Embedded & real-time control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CPP", "DIGITAL"],
    desc: "Running controllers on real hardware: RTOS scheduling, microcontrollers, fixed-point arithmetic, deterministic sample timing, ISRs and DMA, plus motor/power-electronics drivers. Closing the loop in firmware.",
    res:  "UT Austin Embedded Systems - Shape The World, Valvano (audit) | FreeRTOS docs & Mastering the FreeRTOS Kernel (free) | STM32 Motor Control MOOC (free) | Koopman, Better Embedded System Software (~$20)" },
  { id: "ROS2CTRL", phase: "P6", row: 1, label: "ROS2 & ros2_control",
    priority: "critical", kind: "branch", tracks: ["robotics", "automotive", "aerospace"], prereqs: ["CPP", "PY", "LINUX"],
    desc: "ROS 2 architecture (nodes, topics, services, actions, TF) and the ros2_control framework: controller manager, hardware interfaces, real-time control loops, plus MoveIt 2 motion planning and Nav2 autonomous navigation.",
    res:  "Official ROS 2 docs (free) | control.ros.org ros2_control docs (free) | Articulated Robotics ROS2 series (free YT) | MoveIt 2 & Nav2 docs (free) | The Construct ROS2 Control Framework (audit free tier)" },
  { id: "SIM", phase: "P6", row: 2, label: "Simulation & digital twins",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["NUM", "DYN"],
    desc: "Physics-based simulation and digital twins (Gazebo, MuJoCo, Isaac Sim, Simscape) for safe controller development, hardware-in-the-loop testing, and managing the sim-to-real gap before deployment.",
    res:  "Gazebo Sim docs (free) | MuJoCo docs & Colab tutorials, incl. LQR (free) | NVIDIA Isaac Sim / Isaac Lab (free) | Simscape / Simscape Multibody docs (free) | Articulated Robotics \u2014 Gazebo + ROS (free YT)" },
  { id: "PLC", phase: "P6", row: 3, label: "PLC & industrial automation",
    priority: "critical", kind: "branch", tracks: ["industrial"], prereqs: ["DIGITAL"],
    desc: "IEC 61131-3 PLC programming (ladder, structured text, SFC), PLCopen motion function blocks, SCADA/HMI design, and OPC-UA / Modbus connectivity for industrial and process plants.",
    res:  "RealPars PLC fundamentals (free YT) | OpenPLC Editor + Runtime (free) | OPC-UA Online Reference, OPC Foundation (free) | PLCopen Motion Control Part 1 spec (free) | Bolton, Programmable Logic Controllers 6e (~$60)" },
  // ─── P7 ─ Domain & systems ─
  { id: "MOTION", phase: "P7", row: 0, label: "Motion & manipulator control",
    priority: "critical", kind: "branch", tracks: ["robotics"], prereqs: ["ROBKIN", "STSP", "NLCTRL"],
    desc: "Manipulator control: computed-torque/inverse-dynamics, PD-plus-feedforward joint control, operational-space (task-space) control, and trajectory tracking of robot arms with Lyapunov stability analysis.",
    res:  "Modern Robotics Ch.11 Robot Control, Lynch & Park (free) | MR Coursera Course 4: Robot Motion Planning & Control (free trial) | Spong, Hutchinson & Vidyasagar, Robot Modeling and Control 2e (~$140) | Khatib 1987 Operational Space Formulation (free PDF) | Siciliano et al., Robotics: Modelling, Planning and Control, softcover (~$80)" },
  { id: "MOBILE", phase: "P7", row: 1, label: "Mobile & legged robots",
    priority: "desirable", kind: "branch", tracks: ["robotics"], prereqs: ["STSP", "TRAJOPT", "NAV"],
    desc: "Wheeled and legged mobile platforms: odometry, path/trajectory tracking, omnidirectional and nonholonomic kinematics, balance, and convex MPC for dynamic quadruped locomotion over ground reaction forces.",
    res:  "Modern Robotics Ch.13 Wheeled Mobile Robots \u2014 Lynch & Park (free) | Coursera Modern Robotics Course 6: Mobile Manipulation Capstone (audit) | Tedrake Underactuated Robotics, MIT 6.832 (free) | MIT Cheetah 3 Convex MPC \u2014 Di Carlo et al., IROS 2018 (free) | ETH Robot Dynamics lecture notes \u2014 Hutter et al. (free)" },
  { id: "FLTCTRL", phase: "P7", row: 2, label: "Flight & spacecraft control",
    priority: "critical", kind: "branch", tracks: ["aerospace"], prereqs: ["STSP", "NLCTRL", "NLEST"],
    desc: "Fixed-wing and spacecraft control: flight dynamics and linearized trim, attitude kinematics/dynamics with quaternions, cascaded autopilots, guidance loops, and control allocation across redundant actuators.",
    res:  "Beard & McLain UAVbook code + draft (free) | PX4 controller diagrams docs (free) | ArduPilot dev docs (free) | Christopher Lum flight dynamics (free YT) | Markley & Crassidis Spacecraft Attitude (~$90)" },
  { id: "AVCTRL", phase: "P7", row: 3, label: "Autonomous vehicle control",
    priority: "critical", kind: "branch", tracks: ["automotive"], prereqs: ["STSP", "MPC", "NAV"],
    desc: "Self-driving vehicle control: lateral/longitudinal dynamics, the kinematic bicycle model, path-tracking laws (pure pursuit, Stanley, MPC) and integrated planning-and-control feeding actuation.",
    res:  "Rajamani, Vehicle Dynamics and Control (~$280 new / ~$80 used) | Self-Driving Cars Specialization, UToronto / Coursera (audit free) | Autoware docs (free) | MATLAB Automated Driving Toolbox docs (free) | MathWorks Vehicle Path Tracking with MPC (free YT)" },
  { id: "PROCCTRL", phase: "P7", row: 4, label: "Process & industrial control",
    priority: "critical", kind: "branch", tracks: ["industrial"], prereqs: ["CLASSIC", "SYSID"],
    desc: "Process-industry control: process dynamics and FOPDT modeling, PID tuning (IMC/lambda), cascade, feedforward and ratio control, dead-time compensation, and an intro to advanced process control (APC/MPC).",
    res:  "APMonitor / BYU Process Dynamics & Control in Python (free) | Seborg, Edgar, Mellichamp & Doyle, Process Dynamics and Control 4e (~$150) | Astrom & Hagglund, Advanced PID Control, ISA (~$100, used) | controlguru.com \u2014 Practical Process Control (free) | Kuphaldt, Lessons In Industrial Instrumentation, control.com (free)" },
  { id: "GNC", phase: "P7", row: 5, label: "Guidance, navigation & control",
    priority: "desirable", kind: "branch", tracks: ["aerospace", "automotive", "robotics", "estimation"], prereqs: ["NAV", "MPC"],
    desc: "The integrated GNC stack: guidance and trajectory generation, navigation via state estimation and sensor fusion, and inner-loop control with allocation, for drones, autonomous vehicles and spacecraft.",
    res:  "Beard & McLain UAVbook draft + mavsim repo, uavbook.byu.edu (free) | UPenn Aerial Robotics, Kumar (audit) | MATLAB Drone Simulation & Control + Autonomous Navigation series (free YT) | PX4 controller diagrams / ArduPilot dev docs (free) | Markley & Crassidis Spacecraft Attitude, softcover (~$90)" },
  { id: "SAFECTRL", phase: "P7", row: 6, label: "Safety-critical control",
    priority: "critical", kind: "branch", tracks: ["industrial", "automotive", "aerospace"], prereqs: ["EMBED", "NLCTRL"],
    desc: "Functional safety lifecycle (IEC 61508, ISO 26262, DO-178C), SIL/ASIL, fault detection and isolation, fault-tolerant control, and control barrier functions for provable safety constraints.",
    res:  "Ames et al. CBF: Theory & Applications, ECC 2019 / arXiv:1903.11199 (free) | Aaron Ames CBF for Safe Robot Autonomy, ICRA 2022 talk (free YT) | Hobbs Embedded Software Development for Safety-Critical Systems, 2nd ed (~$65) | Blanke et al. Diagnosis & Fault-Tolerant Control, Springer (~$90) | Isermann Fault-Diagnosis Systems, Springer (~$80)" },
  { id: "SYSENG", phase: "P7", row: 7, label: "Control systems engineering",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["EMBED", "MPC"],
    desc: "Systems-engineering view of a control project: requirements capture, model-based design, the V-model, verification and validation, and choosing a control architecture (centralized, hierarchical, supervisory).",
    res:  "MATLAB Tech Talks (free YT) | MathWorks V-model & V&V docs (free) | INCOSE Systems Engineering Handbook 5th ed (~$90) | Coursera Intro to MBSE, Siemens (audit) | SysML.org tutorials (free)" },
  // ─── P8 ─ Frontier & leadership ─
  { id: "LEARNCTRL", phase: "P8", row: 0, label: "Learning & data-driven control",
    priority: "frontier", kind: "elective", tracks: ["robotics", "automotive", "aerospace"], prereqs: ["MPC", "NLCTRL"],
    desc: "Where control meets learning: RL with MPC, imitation learning, differentiable control, and data-driven models (Koopman, SINDy, DMDc, DeePC). Emphasis on safe, constraint-aware learning.",
    res:  "Russ Tedrake Underactuated Robotics (free) | Berkeley CS285 Deep RL \u2014 Levine (free YT) | Steve Brunton Data-Driven Control (free YT) | DeePC paper \u2014 Coulson/Lygeros/Dorfler (free) | L4DC proceedings on PMLR (free)" },
  { id: "LEAD", phase: "P8", row: 1, label: "Technical leadership",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["SYSENG"],
    desc: "Growing influence without managing: architecture and trade-off decisions, design reviews, mentoring, contributing to professional bodies, and communicating control work through writing and conference talks.",
    res:  "Larson Staff Engineer (free web / ~$25 book) | Reilly The Staff Engineer's Path (~$40) | Fournier The Manager's Path (~$40) | IEEE CSS NextCom / Women in Control (CSS membership, paid) | Stein \"Respect the Unstable\" Bode Lecture article (free PDF mirror)" },
  { id: "RESEARCH", phase: "P8", row: 2, label: "Controls research & frontier",
    priority: "frontier", kind: "elective", tracks: ["all"], prereqs: ["NLCTRL", "OPTCTRL"],
    desc: "Reading and publishing research-grade control at CDC/ACC/IFAC: advanced nonlinear, stochastic and optimal control, plus reproducing a recent paper in simulation and writing it up.",
    res:  "IEEE CDC / ACC proceedings on IEEE Xplore (free abstracts) | IEEE Trans. Automatic Control & Automatica (free abstracts) | arXiv eess.SY Systems and Control (free) | Tedrake, Underactuated Robotics MIT 6.832 (free YT + book) | Boyd, Stanford EE263 lectures (free YT) + EE363 notes (free)" },
];

export default {
  id: "control-robotics",
  name: "Control Systems & Robotics",
  srLabel: "Control systems and robotics curriculum grid",
  phases: PHASES,
  tracks: TRACKS,
  courses: COURSES,
};
