// Curriculum data for the Control Systems & Robotics path.
//
// This module holds data only. It is rendered by
// preview-app/src/components/CurriculumGraph.jsx, which owns all the drawing
// logic shared by every career path.
//
// Shape: 8 phases (each about a quarter of study) and 4 specialization tracks.
// Every track takes 2 to 5 courses (spine plus its branch courses) in every
// phase; electives are optional and not counted.
//
// Course fields:
//   id        short stable key, shown on the node
//   phase     which phase column the node sits in
//   row       row within that column; must be 0..n-1 with no gaps or repeats
//   priority  critical | desirable | frontier
//   kind      spine (every track) | branch (chosen track only) | elective
//   tracks    ["all"] for spine nodes, otherwise the track ids that need it
//   prereqs   ids of the nodes that must come first
//   desc      one or two sentences shown in the detail panel
//   res       recommended resources, best match first, separated by "|"

// Phases are drawn left to right in the order listed here.
export const PHASES = [
  { id: "P0", label: "Foundations", subtitle: "Programming & math refresher", color: "#94a3b8" },
  { id: "P1", label: "Phase 1", subtitle: "Signals & classical control", color: "#22d3ee" },
  { id: "P2", label: "Phase 2", subtitle: "Modeling & state-space", color: "#06b6d4" },
  { id: "P3", label: "Phase 3", subtitle: "Estimation & domain foundations", color: "#0ea5e9" },
  { id: "P4", label: "Phase 4", subtitle: "Optimal & predictive control", color: "#6366f1" },
  { id: "P5", label: "Phase 5", subtitle: "Nonlinear & robust control", color: "#8b5cf6" },
  { id: "P6", label: "Phase 6", subtitle: "Real-time & domain control", color: "#14b8a6" },
  { id: "P7", label: "Phase 7", subtitle: "Integration, safety & leadership", color: "#f59e0b" },
];

// Specialization tracks. Node stripes and the filter buttons are coloured
// from this map, and the counts on the page are derived from its size.
export const TRACKS = {
  industrial:{ color: "#d97706", label: "Industrial & process control", short: "Industrial" },
  robotics:  { color: "#059669", label: "Robotics & motion control", short: "Robotics" },
  vehicles:  { color: "#2563eb", label: "Aerospace & automotive", short: "Vehicles" },
  estimation:{ color: "#7c3aed", label: "Estimation & navigation", short: "Estimation" },
};

export const COURSES = [
  // ─── P0 ─ Programming & math refresher ─
  { id: "LINUX", phase: "P0", row: 0, label: "Linux & CLI",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Terminal, bash, file systems, permissions, SSH. The base layer for embedded targets, simulators and robotics middleware.",
    res:  "Linux Journey (free) | MIT Missing Semester (free) | Coursera: The Unix Workbench, Johns Hopkins, audit (free)" },
  { id: "PY", phase: "P0", row: 1, label: "Python",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Core scripting for control: NumPy, SciPy, Matplotlib and the python-control / CasADi ecosystem.",
    res:  "Coursera: Python for Everybody, University of Michigan, audit (free) | Automate the Boring Stuff with Python (free) | python-control docs (free)" },
  { id: "CPP", phase: "P0", row: 2, label: "C++",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Pointers, memory, RAII, STL and real-time patterns. The language of embedded controllers, ROS2 and autopilots.",
    res:  "learncpp.com (free) | A Tour of C++, Stroustrup (paid) | Coursera: C++ for C Programmers, UC Santa Cruz, audit (free)" },
  { id: "MATHCTRL", phase: "P0", row: 3, label: "Engineering math refresher",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Linear algebra, differential equations, calculus and probability at the depth control needs: eigenvalues and the matrix exponential, linear ODEs and the Laplace transform, gradients and linearization, Gaussians and covariance. ODEs and linear algebra are the load-bearing parts.",
    res:  "MIT 18.03SC Differential Equations, OCW (free) | MIT 18.06 Linear Algebra, Strang, OCW (free) | Think Stats, Allen Downey (free)" },
  { id: "GIT", phase: "P0", row: 4, label: "Git & version control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Repos, branches, PRs, CI workflows. Version control for models, controllers and embedded firmware.",
    res:  "git-scm.com tutorial (free) | GitHub Skills (free) | Coursera: Version Control, Meta, audit (free)" },
  // ─── P1 ─ Signals & classical control ─
  { id: "MATLAB", phase: "P1", row: 0, label: "MATLAB & Simulink",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "MATLAB, Simulink, Stateflow and the Control System Toolbox: the industry-standard environment for modeling dynamic systems, designing and tuning controllers, simulating closed loops, and (via Simulink/Embedded Coder) generating embedded code. Learned alongside classical control, where it is first used.",
    res:  "MathWorks MATLAB and Simulink Onramps (free) | MathWorks Control Design Onramp with Simulink (free) | MATLAB Tech Talks on control systems, YouTube (free)" },
  { id: "SIGSYS", phase: "P1", row: 1, label: "Signals & systems",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["MATHCTRL"],
    desc: "Continuous and discrete signals, convolution, Fourier/Laplace/Z transforms, LTI systems and transfer functions, frequency response and sampling. The mathematical language underlying all feedback control.",
    res:  "MIT RES.6-007 Signals and Systems, Oppenheim lectures (free) | Steve Brunton, Fourier Analysis, YouTube (free) | Oppenheim & Willsky, Signals and Systems (paid)" },
  { id: "CLASSIC", phase: "P1", row: 2, label: "Classical control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["SIGSYS"],
    desc: "PID, root locus, Bode/Nyquist, lead-lag compensation, loop shaping, and gain/phase stability margins. Single-loop, single-input/single-output feedback design in continuous time.",
    res:  "Brian Douglas, Control System Lectures, YouTube (free) | Astrom & Murray, Feedback Systems 2e, fbswiki.org (free) | Nise, Control Systems Engineering 8e (paid)" },
  { id: "DIGITAL", phase: "P1", row: 3, label: "Digital control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CLASSIC"],
    desc: "Discretization (ZOH, Tustin, matched pole-zero), z-domain design, sampling and aliasing, anti-alias filtering, and implementing fixed-rate controllers in code with attention to delay and quantization.",
    res:  "Brian Douglas, Discrete control series, YouTube (free) | Franklin, Powell & Workman, Digital Control of Dynamic Systems, e-edition PDF at scsolutions.com (free) | Astrom & Wittenmark, Computer-Controlled Systems, Dover (paid)" },
  // ─── P2 ─ Modeling & state-space ─
  { id: "STSP", phase: "P2", row: 0, label: "State-space control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CLASSIC", "MATHCTRL"],
    desc: "State-space models, controllability and observability, pole placement via state feedback, modal analysis, and Luenberger observers. Separation principle and multivariable (MIMO) design.",
    res:  "Steve Brunton, Control Bootcamp, YouTube (free) | Stanford EE263, Boyd, Linear Dynamical Systems (free) | Friedland, Control System Design, Dover (paid)" },
  { id: "DYN", phase: "P2", row: 1, label: "Dynamics & modeling",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["MATHCTRL"],
    desc: "Newtonian and Lagrangian mechanics, rigid-body kinematics and dynamics. Derive equations of motion for plants and manipulators; linearize about operating points to get state-space models for control design.",
    res:  "MIT OCW 2.003J Dynamics & Control I (free) | Lynch & Park, Modern Robotics ch. 8 preprint (free) | Modern Robotics dynamics lectures, YouTube (free)" },
  { id: "SYSID", phase: "P2", row: 2, label: "System identification",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["STSP", "MATHCTRL"],
    desc: "Building dynamic models from input/output data: least-squares, ARX/ARMAX prediction-error methods, subspace identification, frequency-response estimation, grey-box fitting, plus excitation design and model validation.",
    res:  "Ljung, System Identification: Theory for the User (paid) | MATLAB System Identification Toolbox docs (free) | Steve Brunton, Data-Driven Control: system identification lectures, YouTube (free)" },
  { id: "NUM", phase: "P2", row: 3, label: "Numerical methods & simulation",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["MATHCTRL", "PY"],
    desc: "ODE solvers (Runge-Kutta, stiff/implicit methods), numerical linear algebra, integration error and stability. Simulating dynamical systems accurately and fast in Python/SciPy. The compute layer under every controller.",
    res:  "Steve Brunton, AMATH301 / Engineering Mathematics, YouTube (free) | MIT OCW 18.330 Numerical Analysis (free) | Scientific Python Lectures (free)" },
  { id: "ROBKIN", phase: "P2", row: 4, label: "Robot kinematics & dynamics",
    priority: "critical", kind: "branch", tracks: ["robotics"], prereqs: ["DYN", "MATHCTRL"],
    desc: "Forward and inverse kinematics, DH parameters, screw theory and product of exponentials, the Jacobian, and rigid-body manipulator dynamics (Newton-Euler, Euler-Lagrange). The model of a robot arm.",
    res:  "Lynch & Park, Modern Robotics, free preprint and videos (free) | Coursera: Modern Robotics specialization, Northwestern, audit (free) | QUT Robot Academy, Peter Corke (free)" },
  { id: "PROCMOD", phase: "P2", row: 5, label: "Process modeling & instrumentation",
    priority: "critical", kind: "branch", tracks: ["industrial"], prereqs: ["MATHCTRL", "SIGSYS"],
    desc: "First-principles dynamic models of process units (tanks, heat exchangers, stirred reactors) from mass and energy balances, for continuous and batch operation, plus the instrumentation that closes the loop: transmitters, control valves, 4-20 mA and HART signals, and P&ID and loop diagrams.",
    res:  "Kuphaldt, Lessons In Industrial Instrumentation, control.com (free) | APMonitor / BYU, Process Dynamics and Control in Python (free) | Seborg, Edgar, Mellichamp & Doyle, Process Dynamics and Control 4e, modeling chapters (paid)" },
  // ─── P3 ─ Estimation & domain foundations ─
  { id: "KF", phase: "P3", row: 0, label: "Kalman filtering",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["STSP", "MATHCTRL"],
    desc: "The Kalman filter: optimal linear state estimation via the predict/update recursion, covariance propagation, the Kalman gain, the steady-state form, and tuning the process/measurement noise (Q, R).",
    res:  "Roger Labbe, Kalman and Bayesian Filters in Python (free) | Steve Brunton, Control Bootcamp: Kalman Filter, YouTube (free) | MATLAB Tech Talks, Understanding Kalman Filters, YouTube (free)" },
  { id: "NLEST", phase: "P3", row: 1, label: "Nonlinear estimation (EKF/UKF)",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["KF"],
    desc: "Estimation for nonlinear systems: extended Kalman filter (Jacobian linearization), unscented Kalman filter (sigma points), and particle filters. Process/measurement models, consistency, divergence and tuning.",
    res:  "Roger Labbe, Kalman and Bayesian Filters in Python (free) | Cyrill Stachniss, EKF/UKF/PF lectures, YouTube (free) | Dan Simon, Optimal State Estimation (paid)" },
  { id: "NAV", phase: "P3", row: 2, label: "Navigation & sensor fusion",
    priority: "critical", kind: "branch", tracks: ["estimation", "vehicles", "robotics"], prereqs: ["NLEST"],
    desc: "Strapdown inertial navigation, GNSS positioning, IMU mechanization and INS/GNSS fusion (loose/tight coupling) for position, velocity and attitude. Reference frames, error-state EKF, sensor bias modeling.",
    res:  "Paul Groves, Principles of GNSS, Inertial, and Multisensor Integrated Navigation Systems (paid) | Coursera: State Estimation and Localization for Self-Driving Cars, University of Toronto, audit (free) | VectorNav Inertial Navigation Primer (free)" },
  { id: "SLAM", phase: "P3", row: 3, label: "SLAM",
    priority: "desirable", kind: "branch", tracks: ["robotics", "estimation", "vehicles"], prereqs: ["NLEST"],
    desc: "Simultaneous localization and mapping: EKF-SLAM and FastSLAM, pose-graph/factor-graph optimization, loop closure and data association, with visual and LiDAR front-ends.",
    res:  "Cyrill Stachniss, SLAM Course, YouTube (free) | Thrun, Burgard & Fox, Probabilistic Robotics (paid) | GTSAM + Dellaert, Factor Graphs and GTSAM hands-on tutorial (free)" },
  { id: "ESTADV", phase: "P3", row: 4, label: "Smoothing & tracking",
    priority: "desirable", kind: "branch", tracks: ["estimation", "vehicles"], prereqs: ["NLEST"],
    desc: "Factor-graph batch and fixed-lag smoothing with iSAM2/GTSAM; multi-target tracking and data association (nearest-neighbor, JPDA, MHT) for cluttered sensor streams.",
    res:  "Dellaert & Kaess, Factor Graphs for Robot Perception (free) | GTSAM tutorials, gtsam.org (free) | Bar-Shalom, Li & Kirubarajan, Estimation with Applications to Tracking and Navigation (paid)" },
  { id: "PROCCTRL", phase: "P3", row: 5, label: "Process control & PID tuning",
    priority: "critical", kind: "branch", tracks: ["industrial"], prereqs: ["CLASSIC", "SYSID", "PROCMOD"],
    desc: "Process-industry loop control: FOPDT models from step tests, PID tuning (IMC/lambda), cascade, feedforward and ratio control, dead-time compensation, and the practical failure modes of plant loops (valve nonlinearity, windup, interacting loops).",
    res:  "APMonitor / BYU, Process Dynamics and Control in Python (free) | Doug Cooper, Practical Process Control, controlguru.com (free) | Astrom & Hagglund, Advanced PID Control, ISA (paid)" },
  { id: "PLC", phase: "P3", row: 6, label: "PLC & industrial automation",
    priority: "critical", kind: "branch", tracks: ["industrial"], prereqs: ["DIGITAL"],
    desc: "IEC 61131-3 PLC programming (ladder, structured text, SFC), interlocks and start-up/shutdown sequences, PLCopen motion function blocks, SCADA/HMI design, and connecting a controller to supervision over Modbus TCP or OPC UA.",
    res:  "RealPars PLC fundamentals, YouTube (free) | OpenPLC Editor + Runtime (free) | Bolton, Programmable Logic Controllers 6e (paid)" },
  // ─── P4 ─ Optimal & predictive control ─
  { id: "OPT", phase: "P4", row: 0, label: "Optimization for control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["MATHCTRL", "NUM"],
    desc: "Convex optimization, LP/QP/NLP, KKT conditions, duality and solver internals (interior-point, active-set, ADMM). The optimization engine under optimal control, MPC and estimation.",
    res:  "Boyd & Vandenberghe, Convex Optimization (free) | Stanford EE364a, Boyd lectures, YouTube (free) | OSQP solver docs incl. MPC example (free)" },
  { id: "OPTCTRL", phase: "P4", row: 1, label: "Optimal control (LQR/LQG)",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["STSP", "KF"],
    desc: "LQR, the algebraic Riccati equation, LQG, and the calculus of variations / Pontryagin minimum principle: optimal feedback for linear (and locally nonlinear) systems.",
    res:  "Steve Brunton, Control Bootcamp, LQR/LQG lectures, YouTube (free) | Stanford EE363, Boyd (free) | Anderson & Moore, Optimal Control: Linear Quadratic Methods (free)" },
  { id: "MPC", phase: "P4", row: 2, label: "Model predictive control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["OPTCTRL", "OPT"],
    desc: "Receding-horizon control under constraints: linear and nonlinear MPC, QP/NLP formulations, terminal cost/set design for stability and recursive feasibility, and real-time embedded solvers (OSQP, acados, CasADi).",
    res:  "Rawlings, Mayne & Diehl, Model Predictive Control: Theory, Computation, and Design 2e, author PDF (free) | Borrelli, Bemporad & Morari, Predictive Control for Linear and Hybrid Systems, author PDF (free) | acados, OSQP and do-mpc docs (free)" },
  { id: "TRAJOPT", phase: "P4", row: 3, label: "Trajectory optimization & planning",
    priority: "desirable", kind: "branch", tracks: ["robotics", "vehicles"], prereqs: ["OPT", "OPTCTRL"],
    desc: "Trajectory optimization and motion planning: direct transcription/shooting, direct collocation, iLQR/DDP, sampling-based planners (RRT/PRM), and planning through contact. Maps optimal control onto nonlinear programs.",
    res:  "Tedrake, Underactuated Robotics, ch. 10 and 12 (free) | Matthew Kelly, An Introduction to Trajectory Optimization + OptimTraj (free) | LaValle, Planning Algorithms (free)" },
  // ─── P5 ─ Nonlinear & robust control ─
  { id: "NLCTRL", phase: "P5", row: 0, label: "Nonlinear control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["STSP", "MATHCTRL"],
    desc: "Lyapunov stability and LaSalle's invariance, feedback linearization, backstepping, sliding-mode and passivity-based control. Stability analysis and constructive design for nonlinear systems beyond local linearization.",
    res:  "Khalil, Nonlinear Systems 3e (paid) | Slotine & Li, Applied Nonlinear Control (paid) | Tedrake, Underactuated Robotics, notes and lectures (free)" },
  { id: "ROBUST", phase: "P5", row: 1, label: "Robust control",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["STSP", "OPTCTRL"],
    desc: "Designing for plant uncertainty: H-infinity and mixed-sensitivity synthesis, mu-synthesis with D-K iteration, structured/unstructured uncertainty, sensitivity and robustness margins, and multivariable (MIMO) loop shaping.",
    res:  "Skogestad & Postlethwaite, Multivariable Feedback Control (paid) | MathWorks Robust Control video series, Brian Douglas, YouTube (free) | MATLAB Robust Control Toolbox docs (free)" },
  { id: "ADAPT", phase: "P5", row: 2, label: "Adaptive control",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["NLCTRL", "SYSID"],
    desc: "Controllers that tune themselves online: model-reference adaptive control (MRAC), self-tuning regulators, gain scheduling, and L1 adaptive control. Lyapunov-based adaptation laws, parameter convergence, and robustness modifications.",
    res:  "Ioannou & Sun, Robust Adaptive Control, author PDF (free) | Astrom & Wittenmark, Adaptive Control 2e, Dover (paid) | Slotine & Li, Applied Nonlinear Control, ch. 8 (paid)" },
  { id: "FORCE", phase: "P5", row: 3, label: "Force & impedance control",
    priority: "desirable", kind: "branch", tracks: ["robotics"], prereqs: ["ROBKIN", "NLCTRL"],
    desc: "Interaction control for robots in contact: impedance and admittance control, hybrid force/position control, compliance, and Khatib's operational-space formulation for unified motion and force regulation.",
    res:  "Lynch & Park, Modern Robotics ch. 11 force control, preprint and videos (free) | Siciliano et al., Robotics: Modelling, Planning and Control, ch. 9 (paid) | Hogan, Impedance Control Part I: Theory, 1985 (free)" },
  // ─── P6 ─ Real-time & domain control ─
  { id: "EMBED", phase: "P6", row: 0, label: "Embedded & real-time control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CPP", "DIGITAL"],
    desc: "Running controllers on real hardware: RTOS scheduling, microcontrollers, fixed-point arithmetic, deterministic sample timing, ISRs and DMA, plus motor/power-electronics drivers. Closing the loop in firmware.",
    res:  "UT Austin, Embedded Systems: Shape The World, Valvano, edX audit (free) | FreeRTOS docs and Mastering the FreeRTOS Real Time Kernel (free) | STM32 Motor Control MOOC (free)" },
  { id: "SIM", phase: "P6", row: 1, label: "Simulation & digital twins",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["NUM", "DYN"],
    desc: "Physics-based simulation and digital twins (Gazebo, MuJoCo, Isaac Sim, Simscape) for safe controller development, hardware-in-the-loop testing, and managing the sim-to-real gap before deployment.",
    res:  "Gazebo Sim docs (free) | MuJoCo docs and Colab tutorials, incl. LQR (free) | Simscape / Simscape Multibody docs (free)" },
  { id: "ROS2CTRL", phase: "P6", row: 2, label: "ROS2 & ros2_control",
    priority: "critical", kind: "branch", tracks: ["robotics", "vehicles"], prereqs: ["CPP", "PY", "LINUX"],
    desc: "ROS 2 architecture (nodes, topics, services, actions, TF) and the ros2_control framework: controller manager, hardware interfaces, real-time control loops, plus MoveIt 2 motion planning and Nav2 autonomous navigation.",
    res:  "Official ROS 2 docs (free) | control.ros.org ros2_control docs (free) | Articulated Robotics ROS 2 series, YouTube (free)" },
  { id: "MOTION", phase: "P6", row: 3, label: "Motion & manipulator control",
    priority: "critical", kind: "branch", tracks: ["robotics"], prereqs: ["ROBKIN", "STSP", "NLCTRL"],
    desc: "Manipulator control: computed-torque/inverse-dynamics, PD-plus-feedforward joint control, operational-space (task-space) control, and trajectory tracking of robot arms with Lyapunov stability analysis.",
    res:  "Lynch & Park, Modern Robotics ch. 11 Robot Control (free) | Coursera: Modern Robotics Course 4, Robot Motion Planning and Control, audit (free) | Spong, Hutchinson & Vidyasagar, Robot Modeling and Control 2e (paid)" },
  { id: "FLTCTRL", phase: "P6", row: 4, label: "Flight & spacecraft control",
    priority: "critical", kind: "branch", tracks: ["vehicles"], prereqs: ["STSP", "NLCTRL", "NLEST"],
    desc: "Fixed-wing and spacecraft control: flight dynamics and linearized trim, attitude kinematics/dynamics with quaternions, cascaded autopilots, guidance loops, and control allocation across redundant actuators.",
    res:  "Beard & McLain, UAVbook code and draft, mavsim_public (free) | PX4 controller diagrams docs (free) | Markley & Crassidis, Fundamentals of Spacecraft Attitude Determination and Control (paid)" },
  { id: "AVCTRL", phase: "P6", row: 5, label: "Autonomous vehicle control",
    priority: "critical", kind: "branch", tracks: ["vehicles"], prereqs: ["STSP", "MPC", "NAV"],
    desc: "Self-driving vehicle control: lateral/longitudinal dynamics, the kinematic bicycle model, path-tracking laws (pure pursuit, Stanley, MPC) and integrated planning-and-control feeding actuation.",
    res:  "Coursera: Self-Driving Cars Specialization, University of Toronto, audit (free) | Rajamani, Vehicle Dynamics and Control (paid) | Autoware docs (free)" },
  { id: "INDNET", phase: "P6", row: 6, label: "Industrial networks & OT security",
    priority: "desirable", kind: "branch", tracks: ["industrial"], prereqs: ["PLC"],
    desc: "The communication layer of a plant: fieldbus and industrial Ethernet (PROFINET, EtherNet/IP, EtherCAT, Modbus TCP), OPC UA information models, the Purdue / ISA-95 layer model, and securing control networks with IEC 62443 zones and conduits.",
    res:  "Knapp & Langill, Industrial Network Security 2e, Syngress (paid) | CISA ICS Virtual Learning Portal courses (free) | OPC UA Online Reference, OPC Foundation (free)" },
  { id: "BATCH", phase: "P6", row: 7, label: "Batch & distributed automation",
    priority: "desirable", kind: "branch", tracks: ["industrial"], prereqs: ["PLC", "PROCCTRL"],
    desc: "Structuring plant software above the single loop: ISA-88 batch control (physical and procedural models, recipes, equipment phases as state machines) for pharma, food and specialty chemicals, and IEC 61499 function blocks for distributing control logic across networked devices.",
    res:  "Parshall & Lamb, Applying S88: Batch Control from a User's Perspective, ISA (paid) | Eclipse 4diac IDE and IEC 61499 docs (free) | Vyatkin, IEC 61499 Function Blocks for Embedded and Distributed Control Systems Design, ISA (paid)" },
  // ─── P7 ─ Integration, safety & leadership ─
  { id: "SYSENG", phase: "P7", row: 0, label: "Control systems engineering",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["EMBED", "MPC"],
    desc: "Systems-engineering view of a control project: requirements capture, model-based design, the V-model, verification and validation, and choosing a control architecture (centralized, hierarchical, supervisory).",
    res:  "MathWorks V-model and V&V docs, Simulink Test (free) | INCOSE Systems Engineering Handbook 5e (paid) | Coursera: Introduction to Model-Based Systems Engineering, Siemens, audit (free)" },
  { id: "LEAD", phase: "P7", row: 1, label: "Technical leadership",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["SYSENG"],
    desc: "Growing influence without managing: architecture and trade-off decisions, design reviews, mentoring, contributing to professional bodies, and communicating control work through writing and conference talks.",
    res:  "Larson, Staff Engineer, staffeng.com web edition (free) | Reilly, The Staff Engineer's Path (paid) | Stein, Respect the Unstable, Bode Lecture article (free)" },
  { id: "GNC", phase: "P7", row: 2, label: "Guidance, navigation & control",
    priority: "desirable", kind: "branch", tracks: ["vehicles", "robotics", "estimation"], prereqs: ["NAV", "MPC"],
    desc: "The integrated GNC stack: guidance and trajectory generation, navigation via state estimation and sensor fusion, and inner-loop control with allocation, for drones, autonomous vehicles and spacecraft.",
    res:  "Beard & McLain, UAVbook draft + mavsim_public repo, uavbook.byu.edu (free) | MATLAB Drone Simulation and Control + Autonomous Navigation series, YouTube (free) | PX4 controller diagrams and ArduPilot dev docs (free)" },
  { id: "MOBILE", phase: "P7", row: 3, label: "Mobile & legged robots",
    priority: "desirable", kind: "branch", tracks: ["robotics"], prereqs: ["STSP", "TRAJOPT", "NAV"],
    desc: "Wheeled and legged mobile platforms: odometry, path/trajectory tracking, omnidirectional and nonholonomic kinematics, balance, and convex MPC for dynamic quadruped locomotion over ground reaction forces.",
    res:  "Lynch & Park, Modern Robotics ch. 13 Wheeled Mobile Robots (free) | Tedrake, Underactuated Robotics, MIT 6.832 (free) | Di Carlo et al., MIT Cheetah 3 Convex MPC, IROS 2018 (free)" },
  { id: "SAFECTRL", phase: "P7", row: 4, label: "Safety-critical control",
    priority: "critical", kind: "branch", tracks: ["industrial", "vehicles"], prereqs: ["EMBED", "NLCTRL"],
    desc: "Functional safety lifecycle (IEC 61508, IEC 61511 safety instrumented systems, ISO 26262, DO-178C), SIL/ASIL, fault detection and isolation, fault-tolerant control, and control barrier functions for provable safety constraints.",
    res:  "Ames et al., Control Barrier Functions: Theory and Applications, ECC 2019, arXiv:1903.11199 (free) | Hobbs, Embedded Software Development for Safety-Critical Systems 2e (paid) | Isermann, Fault-Diagnosis Systems, Springer (paid)" },
  { id: "APC", phase: "P7", row: 5, label: "Advanced process control",
    priority: "desirable", kind: "branch", tracks: ["industrial"], prereqs: ["PROCCTRL", "MPC"],
    desc: "Advanced process control as plants run it: multivariable industrial MPC on step-response models, steady-state targets and move suppression, inferential (soft) sensors, real-time optimization, and control-performance monitoring to find the loops worth fixing.",
    res:  "Seborg, Edgar, Mellichamp & Doyle, Process Dynamics and Control 4e, MPC and real-time optimization chapters (paid) | APMonitor / BYU, Dynamic Optimization course, Hedengren (free) | Qin & Badgwell, A survey of industrial model predictive control technology, Control Engineering Practice 2003" },
  { id: "LEARNCTRL", phase: "P7", row: 6, label: "Learning & data-driven control",
    priority: "frontier", kind: "elective", tracks: ["robotics", "vehicles"], prereqs: ["MPC", "NLCTRL"],
    desc: "Where control meets learning: RL with MPC, imitation learning, differentiable control, and data-driven models (Koopman, SINDy, DMDc, DeePC). Emphasis on safe, constraint-aware learning.",
    res:  "Tedrake, Underactuated Robotics (free) | Steve Brunton, Data-Driven Control, YouTube (free) | Coulson, Lygeros & Dorfler, Data-Enabled Predictive Control (DeePC), arXiv:1811.05890 (free)" },
  { id: "RESEARCH", phase: "P7", row: 7, label: "Controls research & frontier",
    priority: "frontier", kind: "elective", tracks: ["all"], prereqs: ["NLCTRL", "OPTCTRL"],
    desc: "Reading and publishing research-grade control at CDC/ACC/IFAC: advanced nonlinear, stochastic and optimal control, plus reproducing a recent paper in simulation and writing it up.",
    res:  "arXiv eess.SY, Systems and Control (free) | IEEE CDC and ACC proceedings on IEEE Xplore, abstracts free (paid) | IEEE Transactions on Automatic Control and Automatica, abstracts free (paid)" },
];

export default {
  id: "control-robotics",
  name: "Control Systems & Robotics",
  srLabel: "Control systems and robotics curriculum grid",
  phases: PHASES,
  tracks: TRACKS,
  courses: COURSES,
};
