// Curriculum data for the Edge AI / Physical AI path.
//
// This module holds data only. It is rendered by
// preview-app/src/components/CurriculumGraph.jsx, which owns all the drawing
// logic shared by the four career paths.
//
// Course fields:
//   id        short stable key, shown on the node
//   phase     which phase column the node sits in
//   row       row within that column; must be 0..n-1 with no gaps or repeats
//   priority  critical | desirable | frontier
//   kind      spine (every track) | branch (chosen track only) | elective
//   tracks    ["all"] for spine nodes, otherwise the track ids that need it
//   prereqs   ids of the nodes that must come first
//   desc      one or two sentences shown in the detail panel
//   res       recommended resources, separated by "|"

// Phases are drawn left to right in the order listed here.
export const PHASES = [
  { id: "P0", label: "Foundations", subtitle: "Prerequisites",     color: "#94a3b8" },
  { id: "P1", label: "Phase 1",     subtitle: "Core ML & Tools",   color: "#22d3ee" },
  { id: "P2", label: "Phase 2",     subtitle: "DL & Operations",   color: "#06b6d4" },
  { id: "P3", label: "Phase 3",     subtitle: "Vision & Export",   color: "#8b5cf6" },
  { id: "P4", label: "Phase 4",     subtitle: "Optimization",      color: "#a78bfa" },
  { id: "P5", label: "Phase 5",     subtitle: "Deploy & Build",    color: "#34d399" },
  { id: "P6", label: "Phase 6",     subtitle: "Integration",       color: "#10b981" },
  { id: "P7", label: "Phase 7",     subtitle: "Architecture",      color: "#f59e0b" },
  { id: "P8", label: "Phase 8",     subtitle: "Frontier & Lead",   color: "#fb923c" },
];

// Specialization tracks. Node stripes and the filter buttons are coloured
// from this map, and the counts on the page are derived from its size.
export const TRACKS = {
  edge:     { color: "#2563eb", label: "Edge AI deployer",            short: "Edge"      },
  robotics: { color: "#059669", label: "Robotics / Physical AI",      short: "Robotics"  },
  compiler: { color: "#7c3aed", label: "Compiler & kernels",          short: "Compiler"  },
  safety:   { color: "#d97706", label: "Industrial functional-safety", short: "Safety"   },
  platform: { color: "#0ea5e9", label: "ML platform & data infra",     short: "Platform"  },
};

export const COURSES = [
  // ─── P0 ─ Foundations (spine) ─────────────────────────────────────────
  { id: "LINUX", phase: "P0", row: 0, label: "Linux & CLI",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Terminal, bash, file systems, permissions, SSH. Foundation for all deployment.",
    res:  "Linux Journey (free) | MIT Missing Semester (free) | Coursera: Unix Workbench, JHU" },
  { id: "PY", phase: "P0", row: 1, label: "Python",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Core language for ML. Variables, functions, OOP, NumPy, pandas, matplotlib.",
    res:  "Coursera: Python for Everybody, UMich | Book: Automate the Boring Stuff (free) | python.org tutorial" },
  { id: "CPP", phase: "P0", row: 2, label: "C++",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Pointers, memory management, OOP, STL. Essential for TensorRT, ROS2, CUDA, kernels.",
    res:  "Coursera: C++ for C Programmers, UCSC | learncpp.com (free) | Book: A Tour of C++, Stroustrup" },
  { id: "LA", phase: "P0", row: 3, label: "Linear algebra",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Vectors, matrices, eigenvalues, SVD. The math behind every neural network.",
    res:  "3Blue1Brown: Essence of Linear Algebra (free YT) | Khan Academy (free) | MIT 18.06 Strang (free YT)" },
  { id: "CALC", phase: "P0", row: 4, label: "Calculus",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Derivatives, chain rule, partial derivatives, gradients. Required for backpropagation.",
    res:  "3Blue1Brown: Essence of Calculus (free YT) | Khan Academy (free) | Coursera: Math for ML, Imperial" },
  { id: "PROB", phase: "P0", row: 5, label: "Probability & statistics",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Bayes theorem, distributions, hypothesis testing, MLE.",
    res:  "Coursera: Statistics with Python, UMich | Book: Think Stats (free) | Khan Academy (free)" },
  { id: "GIT", phase: "P0", row: 6, label: "Git & version control",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Repos, branches, merging, PRs, GitHub workflows.",
    res:  "git-scm.com tutorial (free) | GitHub Skills (free) | Coursera: Version Control, Meta" },

  { id: "ENGLISH", phase: "P0", row: 7, label: "English working fluency",
    priority: "desirable", kind: "elective", tracks: ["all"],
    prereqs: [],
    desc: "Reading papers and docs, writing design notes, and holding technical discussions in English. A continuous lane rather than a phase, because most primary sources and the widest job market are English-first.",
    res:  "Any structured B2 to C1 program | Practice: write every project README and design note in English, why: output beats consumption | Read arXiv abstracts daily (free)" },

  // ─── P1 ─ Core ML & Tools (spine) ────────────────────────────────────
  { id: "ML", phase: "P1", row: 0, label: "Machine learning",
    priority: "critical", kind: "spine", tracks: ["all"],
    prereqs: ["PY","LA","CALC","PROB"],
    desc: "Supervised/unsupervised, regression, classification, clustering, evaluation, scikit-learn.",
    res:  "Coursera: ML Specialization, Andrew Ng | Book: Hands-On ML, Géron | fast.ai Practical Deep Learning for Coders (free)" },
  { id: "DOC", phase: "P1", row: 1, label: "Docker & CI/CD",
    priority: "critical", kind: "spine", tracks: ["all"],
    prereqs: ["LINUX","GIT"],
    desc: "Containers, Dockerfiles, Compose, GitHub Actions, basic CI/CD pipelines.",
    res:  "Docker getting started (free) | Coursera: IBM DevOps & SWE | GitHub Actions docs (free)" },
  { id: "AICODE", phase: "P1", row: 2, label: "AI-assisted dev workflows",
    priority: "desirable", kind: "elective", tracks: ["all"],
    prereqs: ["LINUX","GIT","PY"],
    desc: "Claude Code (CLI, hooks, slash commands, sub-agents, MCP), prompt design for coding tasks, agent setup. Productivity multiplier across the rest of the roadmap.",
    res:  "Anthropic Claude Code docs (free) | Anthropic prompt engineering guide (free) | MCP docs (free) | Anthropic Academy, incl. the Claude Code in Action course (free)" },

  { id: "PIPE", phase: "P1", row: 3, label: "Data pipelines & SQL",
    priority: "critical", kind: "branch", tracks: ["platform"],
    prereqs: ["PY","LINUX"],
    desc: "Batch ETL and ELT, SQL at analytical scale, orchestration with Airflow or Dagster, data-quality tests and schema contracts. The substrate every ML system feeds on.",
    res:  "Data Engineering Zoomcamp (free) | Book: Fundamentals of Data Engineering, Reis & Housley | dbt docs (free), why: the standard for tested, version-controlled transforms" },

  // ─── P2 ─ Deep Learning & Operations ─────────────────────────────────
  { id: "DL", phase: "P2", row: 0, label: "Deep learning & PyTorch",
    priority: "critical", kind: "spine", tracks: ["all"],
    prereqs: ["ML"],
    desc: "Neural networks, CNNs, RNNs, backprop, regularization, transfer learning. PyTorch framework.",
    res:  "Coursera: DL Specialization, Andrew Ng | fast.ai (free) | PyTorch tutorials (free)" },
  { id: "MLOPS", phase: "P2", row: 1, label: "MLOps fundamentals",
    priority: "critical", kind: "spine", tracks: ["all"],
    prereqs: ["ML","DOC"],
    desc: "MLflow, experiment tracking, model serving (FastAPI), monitoring, data drift, CI/CD for ML.",
    res:  "Coursera: Machine Learning in Production, Andrew Ng, why: the successor to the retired MLOps Specialization | MLOps Zoomcamp (free) | Book: Designing ML Systems, Chip Huyen" },
  { id: "CUDA", phase: "P2", row: 2, label: "CUDA & GPU computing",
    priority: "desirable", kind: "branch", tracks: ["edge","robotics","compiler"],
    prereqs: ["CPP","LA"],
    desc: "GPU programming, kernels, memory hierarchy, parallelism. Critical for the compiler track; useful but no longer required for TensorRT, which is why the catalog rates it desirable and leaves raising it to the reader.",
    res:  "NVIDIA DLI: Fundamentals of Accelerated Computing with Modern CUDA C++ (paid) | Coursera: GPU Programming Spec" },

  { id: "LAKE", phase: "P2", row: 3, label: "Lakehouse & warehouse",
    priority: "critical", kind: "branch", tracks: ["platform"],
    prereqs: ["PIPE"],
    desc: "Columnar storage, partitioning, open table formats (Delta, Iceberg, Hudi) and warehouse modelling. Where training data lives once it outgrows files.",
    res:  "Apache Iceberg docs (free) | Delta Lake docs (free) | Book: The Data Warehouse Toolkit, Kimball, why: dimensional modelling still underpins every analytical layer" },

  // ─── P3 ─ Vision, Models & Export ────────────────────────────────────
  { id: "CV", phase: "P3", row: 0, label: "Computer vision",
    priority: "critical", kind: "branch", tracks: ["edge","robotics","safety"],
    prereqs: ["DL"],
    desc: "Image processing (OpenCV), detection (YOLO), segmentation, tracking. Classical + DL approaches.",
    res:  "Hugging Face CV Course (free) | Stanford CS231n (free YT) | Book: DL for Vision Systems, Elgendy" },
  { id: "ONNX", phase: "P3", row: 1, label: "ONNX & model export",
    priority: "critical", kind: "spine", tracks: ["all"],
    prereqs: ["DL"],
    desc: "Export PyTorch/TF models to ONNX. Graph optimization, operator support, runtime inference.",
    res:  "ONNX Runtime docs (free) | ONNX GitHub tutorials (free)" },
  { id: "LLM", phase: "P3", row: 2, label: "LLM fundamentals",
    priority: "critical", kind: "branch", tracks: ["edge","robotics","compiler","platform"],
    prereqs: ["DL"],
    desc: "Transformer architecture, attention mechanism, tokenization, prompting, context windows.",
    res:  "Coursera: GenAI with LLMs, DeepLearning.AI + AWS | Karpathy: Let's build GPT (free YT)" },

  { id: "STREAM", phase: "P3", row: 3, label: "Real-time streaming",
    priority: "critical", kind: "branch", tracks: ["platform","edge"],
    prereqs: ["PIPE","DOC"],
    desc: "Kafka or Pulsar, stream processing with Flink or Spark Structured Streaming, delivery semantics, windowing and backpressure. The path from a sensor or event to a model in seconds.",
    res:  "Apache Flink docs (free) | Confluent Kafka tutorials (free) | Book: Designing Data-Intensive Applications, Kleppmann, why: the clearest treatment of streams versus tables" },

  // ─── P4 ─ Optimization & Specialization ──────────────────────────────
  { id: "TRT", phase: "P4", row: 0, label: "TensorRT",
    priority: "critical", kind: "branch", tracks: ["edge","robotics","compiler"],
    prereqs: ["ONNX","CPP"],
    desc: "NVIDIA inference optimizer. FP16/INT8 quantization, calibration, profiling, C++ and Python APIs.",
    res:  "TensorRT docs and quick-start samples (free) | Jetson AI Lab tutorials (free) | Udemy: TensorRT/ONNX Course (~$15)" },
  { id: "VIT", phase: "P4", row: 1, label: "Vision Transformers",
    priority: "critical", kind: "branch", tracks: ["edge","robotics"],
    prereqs: ["CV"],
    desc: "ViT architecture, CLIP (zero-shot), SAM and SAM 2 (promptable segmentation), DINOv2/v3 (self-supervised features).",
    res:  "Hugging Face CV Course (free) | Papers: ViT, CLIP, SAM on arxiv (free)" },
  { id: "RAG", phase: "P4", row: 2, label: "RAG & vector DBs",
    priority: "critical", kind: "branch", tracks: ["edge"],
    prereqs: ["LLM"],
    desc: "Retrieval-augmented generation, embeddings, vector databases (Chroma, Pinecone), chunking.",
    res:  "DeepLearning.AI: LangChain for LLM Application Development (free) | DeepLearning.AI: Building and Evaluating Advanced RAG (free), why: it covers whether retrieval actually works, not just how to wire it | LangChain docs (free)" },
  { id: "FINE", phase: "P4", row: 3, label: "LLM fine-tuning",
    priority: "desirable", kind: "branch", tracks: ["edge","robotics"],
    prereqs: ["LLM"],
    desc: "LoRA/QLoRA, RLHF, instruction tuning, evaluation frameworks.",
    res:  "DeepLearning.AI short courses on fine-tuning (free) | Coursera: GenAI Engineering, IBM | Hugging Face PEFT docs (free), why: LoRA/QLoRA are what you will actually run" },
  { id: "SF", phase: "P4", row: 4, label: "Sensor fusion",
    priority: "desirable", kind: "branch", tracks: ["edge","robotics"],
    prereqs: ["CV","PROB"],
    desc: "Camera + LiDAR + IMU. Kalman filters, particle filters, point clouds, SLAM basics.",
    res:  "Coursera: Self-Driving Cars, U Toronto | Cyrill Stachniss (free YT) | Book: Probabilistic Robotics" },
  { id: "TFLITE", phase: "P4", row: 5, label: "LiteRT & OpenVINO",
    priority: "desirable", kind: "branch", tracks: ["edge","safety"],
    prereqs: ["ONNX"],
    desc: "Cross-platform edge: LiteRT (formerly TensorFlow Lite, with LiteRT for Microcontrollers on MCUs), OpenVINO for Intel. Alternative to the NVIDIA stack.",
    res:  "Edge Impulse free tier | LiteRT docs (free) | OpenVINO docs (free) | Book: TinyML, Warden" },
  { id: "KERNEL", phase: "P4", row: 6, label: "GPU kernels & profiling",
    priority: "critical", kind: "branch", tracks: ["compiler"],
    prereqs: ["CUDA","CPP"],
    desc: "Triton language, CUTLASS, Nsight Systems / Compute, NVTX. Authoring custom kernels and profile-driven optimization.",
    res:  "Triton tutorials (free) | CUTLASS GitHub (free) | NVIDIA Nsight Compute docs (free) | MIT 6.5940 TinyML and Efficient AI Computing (free lectures), why: the best structured course on pruning, quantization and distillation" },
  { id: "RL", phase: "P4", row: 7, label: "RL & imitation learning",
    priority: "critical", kind: "branch", tracks: ["robotics"],
    prereqs: ["DL"],
    desc: "Policy gradient (PPO), behavior cloning, diffusion policies, vision-language-action (VLA) models. The modern policy-learning stack for robots.",
    res:  "Berkeley CS285 (free YT) | OpenAI Spinning Up (free) | DeepMind RL course (free) | Diffusion Policy paper (free)" },

  { id: "GEO3D", phase: "P4", row: 8, label: "3D geometry & SLAM",
    priority: "critical", kind: "branch", tracks: ["robotics","edge"],
    prereqs: ["CV","LA"],
    desc: "Camera models and calibration, epipolar geometry, triangulation, point clouds and registration, visual odometry and SLAM back ends. The bridge from pixels to a metric world model.",
    res:  "Cyrill Stachniss: Photogrammetry & SLAM lectures, YouTube (free), why: the clearest free lecture series on the subject | Gao Xiang: Introduction to Visual SLAM, book plus code | Barfoot: State Estimation for Robotics, free PDF, why: the rigorous reference for pose estimation" },

  { id: "EVAL", phase: "P4", row: 9, label: "AI evaluation",
    priority: "critical", kind: "branch", tracks: ["edge","platform"],
    prereqs: ["LLM","ML"],
    desc: "Task-specific benchmarks, LLM-as-judge and its failure modes, regression suites, human-review design, offline versus online evaluation. The discipline that decides whether a model change was an improvement or a regression.",
    res:  "DeepLearning.AI: Building and Evaluating Advanced RAG (free) | Book: AI Engineering, Chip Huyen, why: the most practical published treatment of evaluation | OpenAI Evals and Ragas repos (free)" },

  { id: "FEAT", phase: "P4", row: 10, label: "Feature store & training data",
    priority: "desirable", kind: "branch", tracks: ["platform"],
    prereqs: ["LAKE","MLOPS"],
    desc: "Offline and online feature parity, point-in-time correctness, backfills, and reuse across models. The fix for training and serving skew once more than one model shares data.",
    res:  "Feast docs (free) | Book: Designing Machine Learning Systems, Chip Huyen, why: the feature chapter frames the skew problem best | Databricks feature engineering docs (free), why: where Tecton's managed feature platform ended up in 2025" },

  { id: "TSDB", phase: "P4", row: 11, label: "IoT & time-series data",
    priority: "desirable", kind: "branch", tracks: ["platform","edge"],
    prereqs: ["STREAM"],
    desc: "Time-series storage and downsampling, MQTT and OPC UA ingestion, edge buffering under intermittent connectivity, and industrial historians. The data layer of an industrial edge deployment.",
    res:  "TimescaleDB and InfluxDB docs (free) | Eclipse Mosquitto MQTT tutorials (free) | OPC UA specification overview (free), why: the protocol most plant equipment actually speaks" },

  // ─── P5 ─ Deploy & Build ─────────────────────────────────────────────
  { id: "JET", phase: "P5", row: 0, label: "Jetson & edge deploy",
    priority: "critical", kind: "branch", tracks: ["edge","robotics"],
    prereqs: ["TRT","DOC"],
    desc: "NVIDIA Jetson platform. JetPack SDK, DeepStream, video analytics. Production edge deployment.",
    res:  "NVIDIA Jetson tutorials and Jetson AI Lab (free) | NVIDIA DLI Jetson courses (paid) | Book: AI at the Edge, Situnayake | HW: Orin Nano Super dev kit, ~$399" },
  { id: "AGENT", phase: "P5", row: 1, label: "Multi-agent systems",
    priority: "desirable", kind: "branch", tracks: ["edge","platform"],
    prereqs: ["RAG","MLOPS"],
    desc: "LangGraph, CrewAI, MCP protocol. State management, guardrails, observability for agents.",
    res:  "Coursera: IBM RAG and Agentic AI Prof Cert | DeepLearning.AI: Multi AI Agent Systems with crewAI (free) | LangGraph docs | MCP docs" },
  { id: "ROS2", phase: "P5", row: 2, label: "ROS2",
    priority: "critical", kind: "branch", tracks: ["robotics"],
    prereqs: ["CPP","PY","LINUX"],
    desc: "Robot Operating System 2. Nodes, topics, services, Nav2, Gazebo simulation. C++ and Python.",
    res:  "Udemy: ROS2 for Beginners (~$15) | The Construct (free tier) | docs.ros.org | Book: Intro to ROS2, Martín Rico" },
  { id: "DOMAIN", phase: "P5", row: 3, label: "Domain vertical",
    priority: "critical", kind: "spine", tracks: ["all"],
    prereqs: ["CV","ML"],
    desc: "Pick ONE: Industrial/Mining, Automotive, Medical, or Energy. Domain = salary moat.",
    res:  "Coursera: domain specializations | Industry conferences | Professional communities" },

  { id: "SERVE", phase: "P5", row: 4, label: "LLM serving & inference",
    priority: "critical", kind: "branch", tracks: ["platform","edge"],
    prereqs: ["LLM","DOC"],
    desc: "vLLM and SGLang, continuous batching, KV-cache management, quantized serving, streaming responses, and latency and cost budgets under real traffic.",
    res:  "vLLM docs (free), why: the reference implementation of paged attention | SGLang docs (free) | Book: AI Engineering, Chip Huyen" },

  { id: "DATAENG", phase: "P5", row: 5, label: "Data engine & synthetic data",
    priority: "desirable", kind: "branch", tracks: ["edge","robotics","platform"],
    prereqs: ["CV"],
    desc: "The loop that turns deployed failures into training data: mining hard cases, active learning, labelling pipelines, and synthetic or simulated data to cover the long tail.",
    res:  "NVIDIA Omniverse Replicator docs (free) | Voxel51 FiftyOne (free), why: the practical tool for curating and slicing image datasets | Published data-engine talks from AV teams (free)" },

  // ─── P6 ─ Integration ────────────────────────────────────────────────
  { id: "VLM", phase: "P6", row: 0, label: "Vision-language models",
    priority: "critical", kind: "branch", tracks: ["edge","robotics"],
    prereqs: ["VIT","JET"],
    desc: "Multimodal AI on edge. Deploy VLMs on Jetson using TensorRT Edge-LLM SDK (C++ runtime).",
    res:  "Jetson AI Lab: TensorRT Edge-LLM tutorial (free), why: the fastest path to a VLM on real hardware | TensorRT Edge-LLM docs, nvidia.github.io/TensorRT-Edge-LLM (free) | NVIDIA blog: Edge AI on Jetson, LLMs, VLMs and foundation models (free)" },
  { id: "ISAAC", phase: "P6", row: 1, label: "NVIDIA Isaac Sim",
    priority: "desirable", kind: "branch", tracks: ["robotics"],
    prereqs: ["ROS2","JET"],
    desc: "Sim-to-real transfer. Train robot policies in simulation, deploy on Jetson with TensorRT.",
    res:  "NVIDIA DLI: Introduction to Robotic Simulations in Isaac Sim (paid) | Isaac Lab on GitHub (free) | Isaac GR00T deployment guide, GitHub (free)" },
  { id: "DSLM", phase: "P6", row: 2, label: "Domain-specific models",
    priority: "desirable", kind: "branch", tracks: ["edge","robotics","safety"],
    prereqs: ["FINE","DOMAIN"],
    desc: "Fine-tune foundation models for your vertical. Build moats with proprietary data.",
    res:  "Hugging Face fine-tuning guides (free) | Domain-specific datasets and benchmarks" },
  { id: "SAFE", phase: "P6", row: 3, label: "AI safety & governance",
    priority: "desirable", kind: "elective", tracks: ["edge","robotics","safety"],
    prereqs: ["AGENT"],
    desc: "EU AI Act, adversarial ML, red-teaming, model auditing. High-risk obligations now land Dec 2027 to Aug 2028, after the EU's 2026 Digital Omnibus postponement.",
    res:  "Ethics of AI, U Helsinki (free) | ISO 42001 awareness | Coursera: AI Ethics & Societal Challenges, Lund" },
  { id: "SYSDES", phase: "P6", row: 4, label: "Distributed systems",
    priority: "critical", kind: "spine", tracks: ["all"],
    prereqs: ["MLOPS","DOC"],
    desc: "Replication, partitioning, consistency, streaming, batch. Foundation of scalable AI systems.",
    res:  "Book: Designing Data-Intensive Applications, Kleppmann (MUST READ)" },
  { id: "FSAFETY", phase: "P6", row: 5, label: "Functional safety for ML",
    priority: "critical", kind: "branch", tracks: ["safety"],
    prereqs: ["DOMAIN","MLOPS"],
    desc: "IEC 61508 and ISO 26262 (automotive). SIL/ASIL levels, deterministic inference, safety monitors and safety-case writing. Industrial security lives in its own node, because a safe system and a secure one are different arguments.",
    res:  "IEC 61508 white papers (free) | Book: Functional Safety for Embedded Systems, Hobbs | Safety-Critical AI papers (arxiv)" },
  { id: "SAFRES", phase: "P6", row: 6, label: "AI safety research",
    priority: "desirable", kind: "elective", tracks: ["edge","robotics","compiler","platform","safety"],
    prereqs: ["DL","AGENT"],
    desc: "Mechanistic interpretability, alignment evals, capability evaluations. Research-grade safety: understanding model internals and measuring dangerous capabilities. Distinct from governance (compliance) and red-teaming (adversarial probing).",
    res:  "Anthropic interpretability papers (free) | ARENA curriculum (free) | Apollo Research papers (free) | METR evaluation reports (free) | MATS program applications" },
  { id: "GOVENG", phase: "P6", row: 7, label: "AI governance engineering",
    priority: "critical", kind: "branch", tracks: ["edge","robotics","platform","safety"],
    prereqs: ["MLOPS","SAFE"],
    desc: "Implementing AI governance in production: ISO/IEC 42001 management systems, EU AI Act conformity assessment for high-risk systems, model registries, audit trails, NIST AI RMF mapping. Regulation-driven demand from late 2027 onward, now that the EU deferred the high-risk deadlines to Dec 2027 and Aug 2028.",
    res:  "ISO/IEC 42001 standard | EU AI Act Annex IV (free) | NIST AI RMF Playbook (free) | OECD AI Policy Observatory (free)" },

  { id: "OTSEC", phase: "P6", row: 8, label: "OT & industrial security",
    priority: "desirable", kind: "branch", tracks: ["safety","edge","robotics"],
    prereqs: ["DOMAIN"],
    desc: "IEC 62443, the Purdue model, industrial protocols and segmentation, and securing a model that runs next to a PLC. Split out of functional safety because a safe system and a secure one are different arguments.",
    res:  "ISA/IEC 62443 overview material (free) | CISA ICS advisories (free), why: real incidents beat abstract threat models | Book: Industrial Network Security, Knapp & Langill" },

  // ─── P7 ─ Architecture (mostly spine reconvergence) ──────────────────
  { id: "AIARCH", phase: "P7", row: 0, label: "AI systems architecture",
    priority: "critical", kind: "spine", tracks: ["all"],
    prereqs: ["SYSDES","AGENT","JET"],
    desc: "Edge-cloud design, fleet management, federated learning, multi-model serving, system design.",
    res:  "Book: System Design Interview, Alex Xu (Vol 1&2) | Coursera: Software Architecture, U Alberta" },
  { id: "K8S", phase: "P7", row: 1, label: "Kubernetes for ML",
    priority: "desirable", kind: "branch", tracks: ["platform","edge","robotics"],
    prereqs: ["DOC","MLOPS"],
    desc: "Container orchestration, Helm, Kubeflow, model serving at scale, autoscaling inference.",
    res:  "Coursera: Google Cloud K8s | Kubeflow docs (free) | Book: Kubernetes in Action" },
  { id: "CLOUD", phase: "P7", row: 2, label: "Cloud ML platforms",
    priority: "critical", kind: "branch", tracks: ["platform"],
    prereqs: ["MLOPS","DL"],
    desc: "AWS SageMaker, GCP Vertex AI, Azure ML. Training, serving, and monitoring in the cloud.",
    res:  "Coursera: Google Cloud ML Engineer | AWS ML Specialty prep | Azure ML docs (free)" },

  { id: "CAPPHYS", phase: "P7", row: 3, label: "Capstone: Physical AI",
    priority: "critical", kind: "branch", tracks: ["edge","robotics"],
    prereqs: ["JET","ROS2","GEO3D"],
    desc: "One deployed perception-to-action system on real hardware: a calibrated sensor rig, an optimized model, a control or decision loop, and measured latency and failure behaviour. The proof for a Physical AI profile.",
    res:  "No course. Ship it, document it publicly, and report the numbers that matter: latency, accuracy, power draw, and what broke" },

  { id: "CAPDATA", phase: "P7", row: 4, label: "Capstone: Data platform",
    priority: "critical", kind: "branch", tracks: ["platform"],
    prereqs: ["FEAT","STREAM"],
    desc: "One end-to-end platform slice: ingestion to lakehouse to features to a served model, orchestrated, tested and monitored, with documented data contracts. The proof for a Data and AI platform profile.",
    res:  "No course. Ship it as infrastructure-as-code with the data-quality tests running in CI" },

  // ─── P8 ─ Frontier & Leadership ──────────────────────────────────────
  { id: "LEAD", phase: "P8", row: 0, label: "Technical leadership",
    priority: "desirable", kind: "spine", tracks: ["all"],
    prereqs: ["AIARCH"],
    desc: "Architecture decisions, mentoring, writing, conference talks, open source contributions.",
    res:  "Book: Staff Engineer, Larson | Book: The Manager's Path, Fournier" },
  { id: "NEURO", phase: "P8", row: 1, label: "Neuromorphic computing",
    priority: "frontier", kind: "elective", tracks: ["compiler","edge"],
    prereqs: ["CPP","JET"],
    desc: "Spiking neural networks, Intel Loihi 2, ultra-low-power edge AI. Research-grade today with no established hiring market, and Intel archived its Lava SDK in 2026, so treat the tooling as unstable.",
    res:  "snnTorch tutorials (free), why: an actively maintained SNN framework now that Lava is archived | Book: Neuromorphic Engineering, Springer | Loihi 2 papers (free)" },
  { id: "QUANT", phase: "P8", row: 2, label: "Quantum-AI hybrids",
    priority: "frontier", kind: "elective", tracks: ["compiler"],
    prereqs: ["LA","ML"],
    desc: "Quantum-classical algorithms, optimization, Qiskit, Cirq. See the Quantum AI roadmap for the full path and an honest horizon.",
    res:  "IBM Quantum Learning (free), why: it absorbed the retired Qiskit Textbook | Qiskit docs (free) | Book: Nielsen & Chuang" },
  { id: "BIOAI", phase: "P8", row: 3, label: "Bio-digital / medical AI",
    priority: "frontier", kind: "elective", tracks: ["safety"],
    prereqs: ["CV","FINE"],
    desc: "Medical imaging, computational biology, brain-computer interfaces. Heavily regulated, and entry usually runs through a clinical or research institution.",
    res:  "Coursera: AI for Medicine, DeepLearning.AI | MIT OCW: Comp Biology (free)" },
  { id: "FLEET", phase: "P8", row: 4, label: "AI fleet architect",
    priority: "frontier", kind: "branch", tracks: ["robotics","edge"],
    prereqs: ["AIARCH","ROS2","AGENT"],
    desc: "Managing autonomous robot and agent fleets: over-the-air model updates, staged rollout, per-unit monitoring and remote intervention.",
    res:  "No formal courses, build through projects, open source, and industry experience" },
];

export default {
  id: "edge-ai",
  name: "Edge AI / Physical AI",
  srLabel: "Edge AI curriculum grid",
  phases: PHASES,
  tracks: TRACKS,
  courses: COURSES,
};
