// Curriculum data for the Quantum AI path.
//
// This module holds data only. It is rendered by
// preview-app/src/components/CurriculumGraph.jsx, which owns all the drawing
// logic shared by every career path.
//
// Course fields:
//   id        short stable key, shown on the node
//   phase     which phase column the node sits in
//   row       row within that column; must be 0..n-1 with no gaps or repeats
//   priority  critical | desirable | frontier
//   kind      spine (every track) | branch (chosen track only) | elective
//   tracks    ["all"] for spine nodes, otherwise the track ids that need it
//   prereqs   ids of the nodes that must come first
//   desc      one or two sentences shown in the detail panel
//   res       recommended resources, separated by "|", best match first

// Phases are drawn left to right in the order listed here. Each phase is a
// quarter of study (about 3 months).
export const PHASES = [
  { id: "P0", label: "Foundations", subtitle: "Math, CS & programming", color: "#94a3b8" },
  { id: "P1", label: "Phase 1", subtitle: "Quantum mechanics & qubits", color: "#818cf8" },
  { id: "P2", label: "Phase 2", subtitle: "Circuits, SDKs & QPUs", color: "#6366f1" },
  { id: "P3", label: "Phase 3", subtitle: "Algorithms, VQCs & devices", color: "#8b5cf6" },
  { id: "P4", label: "Phase 4", subtitle: "Noise & advanced algorithms", color: "#a855f7" },
  { id: "P5", label: "Phase 5", subtitle: "Variational methods, QEC & pulses", color: "#d946ef" },
  { id: "P6", label: "Phase 6", subtitle: "Hybrid systems & applications", color: "#ec4899" },
  { id: "P7", label: "Phase 7", subtitle: "Frontier & leadership", color: "#f59e0b" },
];

// Specialization tracks. Node stripes and the filter buttons are coloured
// from this map, and the counts on the page are derived from its size.
export const TRACKS = {
  qml:       { color: "#d946ef", label: "Quantum ML researcher", short: "QML" },
  algo:      { color: "#6366f1", label: "Quantum algorithms", short: "Algorithms" },
  hw:        { color: "#ec4899", label: "Quantum hardware & control stack", short: "Hardware" },
  qec:       { color: "#10b981", label: "Quantum error correction", short: "QEC" },
};

export const COURSES = [
  // ─── P0 ─ Foundations: Math, CS & programming ─
  { id: "PY", phase: "P0", row: 0, label: "Python",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "NumPy/SciPy/Matplotlib and Jupyter: the implementation substrate every quantum SDK (Qiskit, PennyLane, Cirq) is built on and called from.",
    res:  "VanderPlas, Python Data Science Handbook (free) | NumPy & SciPy docs (free) | Jupyter docs (free)" },
  { id: "CLA", phase: "P0", row: 1, label: "Complex linear algebra",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Complex vector spaces, inner products, Hermitian/unitary operators, eigendecomposition, SVD, tensor (Kronecker) products: the literal language of qubits, and beyond what a typical real-valued STEM course covers.",
    res:  "Nielsen & Chuang, ch. 2 (paid) | 3Blue1Brown, Essence of Linear Algebra (free) | IBM Quantum Learning, Basics of Quantum Information (free)" },
  { id: "MATHQ", phase: "P0", row: 2, label: "Calculus, optimization & probability refresher",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "A STEM-degree refresher aimed at quantum work: gradients, gradient-based and gradient-free optimization (the engine under VQE and QAOA), plus expectation, variance and estimation from finite shots, since every measured result is a statistical estimate.",
    res:  "Deisenroth, Faisal & Ong, Mathematics for Machine Learning, ch. 5-7 (free) | Blitzstein, Stat 110 (free) | PennyLane parameter-shift demo (free)" },
  { id: "CS", phase: "P0", row: 3, label: "Algorithms & complexity",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: [],
    desc: "Asymptotics, classical algorithms, P/NP, reductions: the baseline that quantum speedups (Grover, Shor) are measured against, hype versus real advantage.",
    res:  "CLRS, Introduction to Algorithms (paid) | Aaronson, Quantum Computing Since Democritus (paid) | de Wolf, Quantum Computing lecture notes (free)" },
  { id: "CML", phase: "P0", row: 4, label: "Classical machine learning",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["PY", "MATHQ"],
    desc: "Supervised/unsupervised learning, kernels, neural nets, gradient-based training: the classical baseline QML must beat and the hybrid-loop host.",
    res:  "Géron, Hands-On Machine Learning (paid) | scikit-learn docs (free) | Andrew Ng, Machine Learning Specialization (paid)" },
  { id: "CPP", phase: "P0", row: 5, label: "C++",
    priority: "desirable", kind: "elective", tracks: ["hw"], prereqs: [],
    desc: "Performance-critical simulation, FPGA/real-time control firmware, SDK internals: an embedded/C++ background is a direct edge on the hardware and control-stack track.",
    res:  "Stroustrup, A Tour of C++ (paid) | learncpp.com (free) | QICK RFSoC control (free)" },
  // ─── P1 ─ Quantum mechanics & qubits ─
  { id: "QM", phase: "P1", row: 0, label: "Quantum mechanics foundations",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["CLA"],
    desc: "QM postulates as linear algebra: Dirac notation, state vectors, Hermitian observables, unitary evolution, the Born rule, measurement collapse.",
    res:  "IBM Quantum Learning, Basics of Quantum Information (free) | Nielsen & Chuang (paid) | Preskill, Ph219 notes (free)" },
  { id: "QUBIT", phase: "P1", row: 1, label: "Qubits & the Bloch sphere",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["QM"],
    desc: "Single-qubit states, superposition, global vs relative phase, Bloch-sphere geometry, Pauli/rotation gates, single-qubit measurement.",
    res:  "IBM Quantum Learning (free) | PennyLane Codebook (free) | Nielsen & Chuang (paid)" },
  { id: "ENT", phase: "P1", row: 2, label: "Multi-qubit systems & entanglement",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["QUBIT"],
    desc: "Tensor-product state spaces, Bell states, separable vs entangled, the no-cloning theorem, partial measurement and reduced density matrices.",
    res:  "IBM Quantum Learning (free) | Nielsen & Chuang (paid) | Watrous, Theory of Quantum Information (free)" },
  // ─── P2 ─ Circuits, SDKs & QPUs ─
  { id: "GATES", phase: "P2", row: 0, label: "Quantum gates & the circuit model",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["ENT"],
    desc: "Pauli, Hadamard, phase, CNOT, Toffoli; universal gate sets, reversibility, circuit identities and the gate-based computational model.",
    res:  "IBM Quantum Learning (free) | Nielsen & Chuang (paid) | PennyLane Codebook (free)" },
  { id: "SDK", phase: "P2", row: 1, label: "Quantum SDKs & simulators",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["GATES", "PY"],
    desc: "Qiskit/PennyLane/Cirq plus Aer & lightning simulators: build, run, visualize circuits and read counts, the daily quantum programming environment.",
    res:  "IBM Quantum Learning & Qiskit docs (free) | PennyLane Codebook & demos (free) | Qiskit Global Summer School (free)" },
  { id: "QPU", phase: "P2", row: 2, label: "Cloud QPUs & real hardware",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["SDK"],
    desc: "Run on IBM Quantum, AWS Braket and Azure Quantum: queues, shots, Sampler/Estimator primitives, and real backend topology and error limits.",
    res:  "IBM Quantum Learning (free) | Qiskit Runtime primitives docs (free) | AWS Braket docs (paid)" },
  { id: "DJ", phase: "P2", row: 3, label: "Oracles & early algorithms",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["GATES"],
    desc: "Quantum oracles, phase kickback, Deutsch-Jozsa and Bernstein-Vazirani: the interference mechanism that powers every quantum speedup.",
    res:  "IBM Quantum Learning (free) | Nielsen & Chuang ch.1 (paid) | Qiskit Global Summer School (free)" },
  // ─── P3 ─ Algorithms, VQCs & devices ─
  { id: "QFT", phase: "P3", row: 0, label: "QFT & phase estimation",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["GATES"],
    desc: "Quantum Fourier transform and quantum phase estimation: the workhorse subroutine underneath Shor, HHL and much of quantum algorithms.",
    res:  "IBM Quantum Learning (free) | Nielsen & Chuang ch.5 (paid) | Andrew Childs lecture notes (free)" },
  { id: "VQC", phase: "P3", row: 1, label: "Variational & parameterized circuits",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["SDK", "MATHQ"],
    desc: "Parameterized quantum circuits and the variational principle; a classical optimizer in the loop driving hybrid quantum-classical training, the paradigm behind VQE, QAOA, QNNs and every hybrid workload.",
    res:  "PennyLane (free) | Cerezo et al. VQA review (free) | IBM Quantum Learning (free)" },
  { id: "PROTO", phase: "P3", row: 2, label: "Core protocols",
    priority: "desirable", kind: "branch", tracks: ["algo", "hw"], prereqs: ["ENT", "GATES"],
    desc: "Teleportation, superdense coding and entanglement swapping prove entanglement is a usable resource, while BB84 QKD rests on no-cloning and measurement disturbance instead. Teleportation is also the first dynamic circuit: mid-circuit measurement plus a classically conditioned correction, which the control stack must execute in real time.",
    res:  "Nielsen & Chuang ch.1-2 (paid) | IBM Quantum Learning (free) | de Wolf lecture notes (free)" },
  { id: "GROVER", phase: "P3", row: 3, label: "Grover search & amplitude amplification",
    priority: "critical", kind: "branch", tracks: ["algo"], prereqs: ["DJ"],
    desc: "Quadratic-speedup unstructured search, the diffusion operator, and amplitude amplification/estimation as a general-purpose primitive.",
    res:  "IBM Quantum Learning (free) | Nielsen & Chuang ch.6 (paid) | PennyLane Codebook (free)" },
  { id: "BQP", phase: "P3", row: 4, label: "Quantum complexity theory",
    priority: "desirable", kind: "branch", tracks: ["algo"], prereqs: ["DJ", "CS"],
    desc: "BQP and its relation to P/NP, query complexity, and a grounded view of what quantum computers can and cannot speed up.",
    res:  "de Wolf lecture notes (free) | Preskill Ph219 notes (free) | Aaronson lecture notes (free)" },
  { id: "ENCODE", phase: "P3", row: 5, label: "Quantum data encoding",
    priority: "critical", kind: "branch", tracks: ["qml"], prereqs: ["GATES", "CML"],
    desc: "Basis/amplitude/angle encoding and feature maps. The data-loading bottleneck that makes or breaks any quantum ML speedup.",
    res:  "PennyLane demos (free) | Schuld & Petruccione (paid) | Cerezo et al. VQA review (free)" },
  { id: "QKERN", phase: "P3", row: 6, label: "Quantum kernels & quantum SVM",
    priority: "desirable", kind: "branch", tracks: ["qml"], prereqs: ["ENCODE"],
    desc: "Quantum feature maps used as kernels, kernel-target alignment, and a sober look at where quantum kernels might plausibly beat classical ones.",
    res:  "Havlíček et al. 2019 (free) | Schuld & Killoran 2019 (free) | PennyLane kernels demo (free)" },
  { id: "TRANS", phase: "P3", row: 7, label: "Circuit compilation & transpilation",
    priority: "critical", kind: "branch", tracks: ["hw"], prereqs: ["SDK"],
    desc: "Decompose gates to a basis set, route onto a coupling map with SWAPs, run optimization passes: the layer between an abstract circuit and noisy hardware.",
    res:  "Qiskit transpiler docs (free) | IBM Quantum Learning (free) | Cirq docs (free)" },
  { id: "MODAL", phase: "P3", row: 8, label: "Qubit modalities & device physics",
    priority: "critical", kind: "branch", tracks: ["hw"], prereqs: ["QM"],
    desc: "Compare superconducting transmons, trapped ions, photonic, neutral-atom and spin qubits against the DiVincenzo criteria and their trade-offs.",
    res:  "Krantz et al. SC Qubits Guide (free) | Kjaergaard 'State of Play' (free) | Bruzewicz trapped-ion review (free)" },
  // ─── P4 ─ Noise & advanced algorithms ─
  { id: "DENS", phase: "P4", row: 0, label: "Density matrices & open systems",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["QM", "ENT"],
    desc: "Density operators, mixed states, partial trace, and quantum channels (Kraus operators): the math for describing real, noisy qubits.",
    res:  "Nielsen & Chuang ch.2/8 (paid) | Preskill Ph219 notes (free) | QuTiP docs (free)" },
  { id: "SHOR", phase: "P4", row: 1, label: "Shor's algorithm & quantum arithmetic",
    priority: "desirable", kind: "branch", tracks: ["algo"], prereqs: ["QFT"],
    desc: "Period finding via phase estimation, modular-arithmetic circuits, and the integer-factoring threat that breaks RSA on a fault-tolerant machine.",
    res:  "Nielsen & Chuang ch.5 (paid) | IBM Quantum Learning (free) | Andrew Childs lecture notes (free)" },
  { id: "HHL", phase: "P4", row: 2, label: "HHL & quantum linear algebra",
    priority: "desirable", kind: "branch", tracks: ["algo", "qml"], prereqs: ["QFT"],
    desc: "Quantum linear-systems solving, its strict caveats (state prep, sparsity, condition number, readout), and what it really means for quantum ML.",
    res:  "Aaronson 'Read the fine print' (free) | IBM Quantum Learning (free) | Andrew Childs lecture notes (free)" },
  { id: "HSIM", phase: "P4", row: 3, label: "Hamiltonian simulation & Trotterization",
    priority: "critical", kind: "branch", tracks: ["algo", "qml"], prereqs: ["GATES", "QFT"],
    desc: "Simulate e^{-iHt} via Trotter-Suzuki product formulas, their error scaling, and post-Trotter pointers: the algorithm with the clearest quantum advantage.",
    res:  "Childs, Lecture Notes on Quantum Algorithms (free) | Nielsen & Chuang (paid) | PennyLane Hamiltonian-simulation demos (free)" },
  { id: "QNN", phase: "P4", row: 4, label: "Quantum neural networks & gradients",
    priority: "critical", kind: "branch", tracks: ["qml"], prereqs: ["VQC", "ENCODE"],
    desc: "QNN architectures and the parameter-shift rule for analytic hardware gradients; data re-uploading to boost expressivity.",
    res:  "Schuld et al. parameter-shift (free) | Pérez-Salinas data re-uploading (free) | PennyLane (free)" },
  { id: "STAB", phase: "P4", row: 5, label: "Stabilizer formalism & classical simulation",
    priority: "desirable", kind: "branch", tracks: ["algo", "qec"], prereqs: ["GATES", "DENS"],
    desc: "Stabilizer/Clifford formalism, Gottesman-Knill, and tensor-network/MPS simulation: what is classically simulable and the shared language of QEC.",
    res:  "Gottesman stabilizer-codes notes (free) | Google Stim (free) | quimb (free)" },
  { id: "QINFO", phase: "P4", row: 6, label: "Quantum information theory",
    priority: "desirable", kind: "branch", tracks: ["qec"], prereqs: ["DENS"],
    desc: "Fidelity, trace distance, von Neumann entropy, entanglement measures and basic channel capacities: quantifying quantum information.",
    res:  "Watrous, Theory of QI (free) | Nielsen & Chuang ch.9/11/12 (paid) | de Wolf lecture notes (free)" },
  { id: "NOISE", phase: "P4", row: 7, label: "Noise, decoherence & NISQ",
    priority: "critical", kind: "branch", tracks: ["qml", "hw", "qec"], prereqs: ["DENS"],
    desc: "T1/T2 decoherence, gate and readout error, depolarizing and dephasing channels, and what the NISQ era actually constrains.",
    res:  "Preskill 'Quantum Computing in the NISQ era' (free) | Krantz et al. arXiv:1904.06560 (free) | Qiskit Aer noise docs (free)" },
  { id: "CTRL", phase: "P4", row: 8, label: "Control electronics & cryo/RF",
    priority: "critical", kind: "branch", tracks: ["hw"], prereqs: ["MODAL"],
    desc: "AWGs, RF/microwave up- and down-conversion chains, FPGA real-time feedback, and dilution-fridge wiring: the electronic engineer's niche.",
    res:  "Krantz et al. control sections (free) | QICK RFSoC platform (free) | Krinner cryo-wiring paper (free)" },
  // ─── P5 ─ Variational methods, QEC & pulses ─
  { id: "VQE", phase: "P5", row: 0, label: "Variational quantum eigensolver",
    priority: "critical", kind: "branch", tracks: ["qml", "algo"], prereqs: ["VQC"],
    desc: "Estimate molecular ground-state energies with a variational ansatz plus Hamiltonian measurement: the flagship NISQ quantum-chemistry algorithm.",
    res:  "PennyLane qchem (free) | Qiskit Nature (free) | Peruzzo et al. 2014 (free)" },
  { id: "QAOA", phase: "P5", row: 1, label: "QAOA & quantum optimization",
    priority: "critical", kind: "branch", tracks: ["qml", "algo"], prereqs: ["VQC"],
    desc: "Quantum approximate optimization for combinatorial problems (max-cut, QUBO) via alternating cost and mixer layers; depth-p vs quality trade-offs.",
    res:  "Farhi et al. QAOA paper (free) | PennyLane QAOA demo (free) | IBM Quantum Learning (free)" },
  { id: "DEQ", phase: "P5", row: 2, label: "Dequantization & quantum-inspired limits",
    priority: "desirable", kind: "branch", tracks: ["qml", "algo"], prereqs: ["HHL"],
    desc: "The I/O (state-prep/readout) bottleneck and Tang-style dequantization: judging which QML and quantum-linear-algebra speedups actually survive.",
    res:  "Aaronson, Read the Fine Print (free) | Ewin Tang dequantization papers, arXiv (free) | Schuld & Petruccione, ML with Quantum Computers (paid)" },
  { id: "QSVT", phase: "P5", row: 3, label: "QSP, QSVT & qubitization",
    priority: "desirable", kind: "branch", tracks: ["algo"], prereqs: ["QFT", "HHL"],
    desc: "Quantum signal processing, QSVT, LCU and qubitization: the post-2018 framework unifying search, phase estimation, HHL and Hamiltonian simulation.",
    res:  "Martyn et al., Grand Unification of Quantum Algorithms, arXiv (free) | Gilyén-Su-Low-Wiebe QSVT paper + Low-Chuang qubitization (free) | PennyLane QSP/QSVT demos (free)" },
  { id: "BARREN", phase: "P5", row: 4, label: "Trainability & barren plateaus",
    priority: "desirable", kind: "branch", tracks: ["qml"], prereqs: ["QNN"],
    desc: "Exponentially vanishing gradients in deep/expressive circuits: expressibility- and entanglement-induced plateaus, plus mitigation strategies.",
    res:  "McClean et al. 2018 (free) | Cerezo et al. 2021 (free) | PennyLane barren-plateaus demo (free)" },
  { id: "MITIG", phase: "P5", row: 5, label: "Error mitigation",
    priority: "desirable", kind: "branch", tracks: ["qml", "hw"], prereqs: ["NOISE"],
    desc: "Zero-noise extrapolation, probabilistic error cancellation and measurement-error mitigation: squeezing signal out of NISQ devices.",
    res:  "Mitiq docs (free) | Temme et al. ZNE/PEC paper (free) | IBM Quantum error-mitigation docs (free)" },
  { id: "QEC", phase: "P5", row: 6, label: "Quantum error correction",
    priority: "desirable", kind: "branch", tracks: ["qec"], prereqs: ["QINFO", "STAB"],
    desc: "Stabilizer formalism, 3-qubit/Steane/surface codes, syndrome extraction, code distance and thresholds: protecting logical qubits.",
    res:  "Roffe QEC introductory guide (free) | Gottesman stabilizer notes (free) | Nielsen & Chuang ch.10 (paid)" },
  { id: "QECIMPL", phase: "P5", row: 7, label: "Implementing QEC codes & decoders",
    priority: "desirable", kind: "branch", tracks: ["qec"], prereqs: ["QEC"],
    desc: "Build and simulate repetition, Steane and rotated surface codes, extract syndromes and run MWPM/union-find decoders against a noise model.",
    res:  "Roffe, QEC: An Introductory Guide, arXiv (free) | Google Stim (free) | PyMatching decoder (free)" },
  { id: "PULSE", phase: "P5", row: 8, label: "Pulse-level control",
    priority: "critical", kind: "branch", tracks: ["hw"], prereqs: ["GATES", "NOISE"],
    desc: "Map logical gates to microwave/laser pulses: Rabi and Ramsey experiments and GRAPE optimal-control pulse shaping. Qiskit Pulse was retired with Qiskit 2.0, so pulse work now runs through simulation (Qiskit Dynamics, QuTiP) or open control hardware (QICK).",
    res:  "Krantz et al. drive sections (free) | Qiskit Dynamics docs (free), why: the successor to the removed Qiskit Pulse | QuTiP optimal-control (free)" },
  // ─── P6 ─ Hybrid systems & applications ─
  { id: "QARCH", phase: "P6", row: 0, label: "Hybrid quantum-classical architecture",
    priority: "critical", kind: "spine", tracks: ["all"], prereqs: ["QPU", "VQC"],
    desc: "Architect hybrid workloads: classical orchestration around QPU calls, pre/post-processing, shot batching, and honest cost/latency tradeoffs vs classical.",
    res:  "Qiskit Runtime docs (free) | PennyLane demos (free) | Cerezo et al. VQA review (free)" },
  { id: "CHEM", phase: "P6", row: 1, label: "Quantum chemistry & simulation",
    priority: "desirable", kind: "branch", tracks: ["algo", "qml"], prereqs: ["VQE", "HSIM"],
    desc: "Map molecular Hamiltonians to qubits (Jordan-Wigner/Bravyi-Kitaev) and run VQE for ground-state energies; the strongest near-term quantum use case.",
    res:  "Qiskit Nature tutorials (free) | PennyLane qchem demos (free) | OpenFermion (free)" },
  { id: "QOPT", phase: "P6", row: 2, label: "Industrial quantum optimization",
    priority: "desirable", kind: "branch", tracks: ["algo", "qml"], prereqs: ["QAOA"],
    desc: "Cast logistics/scheduling problems as QUBO/Ising, solve via QAOA or annealing, and benchmark honestly against classical solvers that usually still win.",
    res:  "PennyLane QAOA demos (free) | qiskit-addon-opt-mapper docs (free), why: IBM archived the old Qiskit Optimization module in 2026 | D-Wave Ocean docs (free)" },
  { id: "PQC", phase: "P6", row: 3, label: "Post-quantum cryptography",
    priority: "desirable", kind: "branch", tracks: ["algo"], prereqs: ["SHOR"],
    desc: "Shor breaks RSA/ECC once a large fault-tolerant QPU exists; deploy NIST PQC (ML-KEM/ML-DSA/SLH-DSA) now against harvest-now-decrypt-later risk.",
    res:  "NIST FIPS 203/204/205 (free) | Open Quantum Safe / liboqs (free) | Andrew Childs algorithms notes (free)" },
  { id: "RESEST", phase: "P6", row: 4, label: "Fault-tolerance & resource estimation",
    priority: "desirable", kind: "branch", tracks: ["qec"], prereqs: ["QEC"],
    desc: "Estimate logical qubits, T-counts, code distance and overhead for real apps (chemistry, Shor): the honest tool for judging how far FTQC is.",
    res:  "Beverland et al., Assessing requirements to scale to practical quantum advantage, arXiv (free) | Azure Quantum Resource Estimator (free) | Roffe QEC guide (free)" },
  { id: "CHAR", phase: "P6", row: 5, label: "Characterization & calibration",
    priority: "critical", kind: "branch", tracks: ["hw", "qec"], prereqs: ["NOISE", "QPU"],
    desc: "T1/T2 coherence measurement, randomized benchmarking, gate-set and process tomography, and automated qubit and gate calibration.",
    res:  "Qiskit Experiments (free) | Magesan RB papers (free) | pyGSTi gate-set tomography (free)" },
  // ─── P7 ─ Frontier & leadership ─
  { id: "LEAD", phase: "P7", row: 0, label: "Technical leadership",
    priority: "desirable", kind: "spine", tracks: ["all"], prereqs: ["QARCH"],
    desc: "Read and write papers, give talks, contribute to quantum open source, and translate results for non-specialist stakeholders.",
    res:  "arXiv quant-ph + Quantum journal (free) | Qiskit/PennyLane open source (free) | Google Technical Writing (free)" },
  { id: "ADV", phase: "P7", row: 1, label: "Quantum advantage & benchmarking",
    priority: "frontier", kind: "branch", tracks: ["algo", "qml"], prereqs: ["QPU", "QAOA"],
    desc: "Random-circuit sampling, application benchmarks (QED-C), volumetric metrics: rigorously defining and claiming quantum advantage.",
    res:  "QED-C benchmark suite (free) | Google Sycamore + IBM utility papers (free) | Quantum Volume / CLOPS (free)" },
  { id: "QFIN", phase: "P7", row: 2, label: "Quantum computing in finance",
    priority: "desirable", kind: "branch", tracks: ["algo", "qml"], prereqs: ["QAOA", "HHL"],
    desc: "Quantum amplitude estimation for Monte-Carlo pricing/risk (a quadratic speedup on paper) plus portfolio optimization; weigh against a sober value picture.",
    res:  "Qiskit Finance tutorials (free) | IBM Quantum Learning (free) | Andrew Childs algorithms notes (free)" },
  { id: "QMLR", phase: "P7", row: 3, label: "QML research frontier",
    priority: "frontier", kind: "branch", tracks: ["qml"], prereqs: ["QNN", "BARREN"],
    desc: "Provable advantage in learning, quantum data, dequantization, geometric/equivariant QML: with honest skepticism about the hype.",
    res:  "Schuld & Petruccione, Machine Learning with Quantum Computers (paid) | Huang et al. quantum-data papers (free) | PennyLane demos (free)" },
  { id: "FTQC", phase: "P7", row: 4, label: "Fault-tolerant quantum computing",
    priority: "frontier", kind: "branch", tracks: ["qec"], prereqs: ["QEC"],
    desc: "Logical qubits, magic-state distillation, lattice surgery, fault-tolerant thresholds and resource estimation: the path beyond NISQ.",
    res:  "Gottesman FT notes (free) | Roffe QEC guide (free) | Azure Quantum Resource Estimator (free)" },
  { id: "QECR", phase: "P7", row: 5, label: "QEC & decoder research",
    priority: "frontier", kind: "branch", tracks: ["qec"], prereqs: ["QEC"],
    desc: "Surface and LDPC codes, real-time decoders (MWPM, union-find, neural): the frontier where most near-term progress concentrates.",
    res:  "Roffe QEC guide (free) | Stim, Gidney + PyMatching, Higgott (free) | qLDPC + surface-code papers, arXiv (free)" },
  { id: "FPGA", phase: "P7", row: 6, label: "Real-time control & FPGA feedback",
    priority: "critical", kind: "branch", tracks: ["hw"], prereqs: ["CTRL", "NOISE"],
    desc: "FPGA gateware for syndrome extraction and sub-microsecond decode-and-correct feedback, plus classical control co-design: the hardware edge.",
    res:  "QICK FPGA control framework, Fermilab (free) | Krantz et al., Quantum Engineer's Guide to Superconducting Qubits, arXiv:1904.06560 (free) | Qiskit Dynamics & QuTiP (free)" },
];

export default {
  id: "quantum-ai",
  name: "Quantum AI",
  srLabel: "Quantum AI curriculum grid",
  phases: PHASES,
  tracks: TRACKS,
  courses: COURSES,
};
